/*
 * 키워드 데이터
 * - 문자열 항목: 텍스트만 출력
 * - 객체 항목: { ko: 화면 표기, tag: 이미지 프롬프트 태그, g: 허용 성별, natural: 자연 색상 여부 }
 * 키워드를 추가·수정하려면 이 파일만 고치면 됩니다.
 * 이름 목록의 중복(같은 로마자 표기)은 app.js가 불러올 때 자동으로 걸러집니다.
 */

// 영미권 공통 이름 (미국 · 영국에 함께 들어감)
const ANGLO = {
  surnames: [
    ['윌리엄스', 'Williams'], ['브라운', 'Brown'], ['존스', 'Jones'], ['밀러', 'Miller'], ['데이비스', 'Davis'],
    ['윌슨', 'Wilson'], ['앤더슨', 'Anderson'], ['토마스', 'Thomas'], ['테일러', 'Taylor'], ['무어', 'Moore'],
    ['잭슨', 'Jackson'], ['마틴', 'Martin'], ['리', 'Lee'], ['톰슨', 'Thompson'], ['화이트', 'White'],
    ['해리스', 'Harris'], ['클라크', 'Clark'], ['루이스', 'Lewis'], ['로빈슨', 'Robinson'], ['카터', 'Carter'],
    ['로저스', 'Rogers'], ['헤이즈', 'Hayes'], ['도노반', 'Donovan'], ['딜런', 'Dillon'], ['레비', 'Levy'],
    ['레어드', 'Laird'], ['레일리', 'Reilly'], ['로슨', 'Lawson'], ['로웰', 'Lowell'], ['그레이브스', 'Graves'],
    ['그웬', 'Gwynne'], ['길모어', 'Gilmore'], ['베넷', 'Bennett'], ['번스타인', 'Bernstein'], ['베켓', 'Beckett'],
    ['보일', 'Boyle'], ['맥코이', 'McCoy'], ['맥클레인', 'McClain'], ['메이슨', 'Mason'], ['린드버그', 'Lindbergh'],
    ['린든', 'Linden'], ['멜빌', 'Melville'], ['섀넌', 'Shannon'], ['브룩스', 'Brooks'], ['싱클레어', 'Sinclair'],
    ['시모어', 'Seymour'], ['웨버', 'Webber'], ['캐번디시', 'Cavendish'], ['캐롤', 'Carroll'], ['칼라일', 'Carlisle'],
    ['파킨슨', 'Parkinson'], ['프로스트', 'Frost'], ['트레비스', 'Travis'], ['콘스탄틴', 'Constantine'], ['크레인', 'Crane'],
    ['포지', 'Posey'], ['스톤', 'Stone'], ['테이트', 'Tate'], ['발레리', 'Valery'], ['발렌타인', 'Valentine'],
    ['킹', 'King'], ['라이언', 'Ryan'], ['스트라이더', 'Strider'], ['마이어스', 'Myers'], ['코린', 'Corin'],
    ['크롬웰', 'Cromwell'], ['니켈', 'Nickel'], ['퀸', 'Quinn'], ['와이즈먼', 'Wiseman'], ['레이크', 'Lake'],
    ['카메론', 'Cameron'], ['캠벨', 'Campbell'], ['하웰', 'Howell'], ['그린버그', 'Greenberg'],
    ['챈들러', 'Chandler'], ['맥켄지', 'McKenzie'], ['도슨', 'Dawson'], ['피어스', 'Pierce'], ['몽고메리', 'Montgomery'],
    ['랭커스터', 'Lancaster'], ['밴크로프트', 'Bancroft'], ['윈터스', 'Winters'], ['스털링', 'Sterling'], ['해밀턴', 'Hamilton'],
    ['프레스턴', 'Preston'], ['버크', 'Burke'], ['플레처', 'Fletcher'], ['배니스터', 'Bannister'], ['채프먼', 'Chapman'],
    ['브래들리', 'Bradley'], ['허드슨', 'Hudson'], ['맥스웰', 'Maxwell'], ['크로퍼드', 'Crawford'], ['더글러스', 'Douglas'],
    ['헌터', 'Hunter'], ['피츠제럴드', 'Fitzgerald'], ['젠킨스', 'Jenkins'],
    ['워커', 'Walker'], ['홀', 'Hall'], ['앨런', 'Allen'], ['영', 'Young'], ['라이트', 'Wright'],
    ['스콧', 'Scott'], ['그린', 'Green'], ['베이커', 'Baker'], ['애덤스', 'Adams'], ['넬슨', 'Nelson'],
    ['힐', 'Hill'], ['미첼', 'Mitchell'], ['로버츠', 'Roberts'], ['터너', 'Turner'], ['필립스', 'Phillips'],
    ['에반스', 'Evans'], ['에드워즈', 'Edwards'], ['콜린스', 'Collins'], ['스튜어트', 'Stewart'], ['모리스', 'Morris'],
    ['벨', 'Bell'], ['쿠퍼', 'Cooper'], ['하워드', 'Howard'], ['피터슨', 'Peterson'], ['그레이', 'Gray'],
    ['왓슨', 'Watson'], ['우드', 'Wood'], ['반스', 'Barnes'], ['로스', 'Ross'], ['헨더슨', 'Henderson'],
    ['콜먼', 'Coleman'], ['휴스', 'Hughes'], ['프라이스', 'Price'], ['러셀', 'Russell'], ['클라크', 'Clarke'],
    ['로이드', 'Lloyd'], ['베일리', 'Bailey'], ['바커', 'Barker'], ['파커', 'Parker'], ['체임버스', 'Chambers'],
    ['휘트모어', 'Whitmore'], ['킹슬리', 'Kingsley'], ['올드리지', 'Aldridge'], ['나이트', 'Knight'], ['폭스', 'Fox'],
    ['하트', 'Hart'], ['레인', 'Lane'], ['웰스', 'Wells'], ['마시', 'Marsh'], ['헤일', 'Hale'],
    ['리브스', 'Reeves'], ['그랜트', 'Grant'], ['서튼', 'Sutton'], ['해리슨', 'Harrison'], ['헌트', 'Hunt'],
    ['크로우', 'Crowe'], ['리버스', 'Rivers'], ['폰테인', 'Fontaine'], ['셔먼', 'Sherman'], ['러벨', 'Lovell'],
    ['클레어리', 'Cleary'], ['샌더슨', 'Sanderson'], ['에이블', 'Abel'], ['마이어', 'Meyer'], ['위버', 'Weaver'],
    ['윌러드', 'Willard'], ['페리', 'Perry'], ['맥도웰', 'McDowell'],
    ["워렌", "Warren"], ["커틀러", "Cutler"], ["샤프", "Sharp"], ["저드", "Judd"], ["파울러", "Fowler"],
    ["하코트", "Harcourt"], ["워튼", "Wharton"], ["바클레이", "Barclay"], ["크로슬리", "Crossley"], ["케인", "Kane"],
    ["푸트넘", "Putnam"], ["캐닝", "Canning"],
  ],
  male: [
    ['리암', 'Liam'], ['노아', 'Noah'], ['올리버', 'Oliver'], ['일라이저', 'Elijah'], ['로건', 'Logan'],
    ['맥스', 'Max'], ['아이작', 'Isaac'], ['오스카', 'Oscar'], ['제임스', 'James'], ['윌리엄', 'William'],
    ['벤자민', 'Benjamin'], ['루카스', 'Lucas'], ['헨리', 'Henry'], ['테오도르', 'Theodore'], ['잭', 'Jack'],
    ['리바이', 'Levi'], ['알렉산더', 'Alexander'], ['잭슨', 'Jackson'], ['마테오', 'Mateo'], ['다니엘', 'Daniel'],
    ['마이클', 'Michael'], ['메이슨', 'Mason'], ['호레이쇼', 'Horatio'], ['네이선', 'Nathan'], ['나타니엘', 'Nathaniel'],
    ['에반', 'Evan'], ['세바스찬', 'Sebastian'], ['에단', 'Ethan'], ['오웬', 'Owen'], ['사무엘', 'Samuel'],
    ['제이콥', 'Jacob'], ['애셔', 'Asher'], ['제이', 'Jay'], ['콜린', 'Colin'], ['조슈아', 'Joshua'],
    ['다윈', 'Darwin'], ['딜런', 'Dylan'], ['랜돌프', 'Randolph'], ['루이스', 'Louis'], ['사이먼', 'Simon'],
    ['마크', 'Mark'], ['마틴', 'Martin'], ['버나드', 'Bernard'], ['버스터', 'Buster'], ['래리', 'Larry'],
    ['아론', 'Aaron'], ['아벨', 'Abel'], ['매그너스', 'Magnus'], ['아나킨', 'Anakin'], ['어빈', 'Irvin'],
    ['체스터', 'Chester'], ['제이크', 'Jake'], ['칼라일', 'Carlisle'], ['유진', 'Eugene'], ['클레이튼', 'Clayton'],
    ['행크', 'Hank'],
    ['빈센트', 'Vincent'], ['제어드', 'Jared'], ['데미안', 'Damian'], ['콜', 'Cole'], ['아처', 'Archer'],
    ['핀리', 'Finley'], ['실라스', 'Silas'], ['덱스터', 'Dexter'], ['마일스', 'Miles'], ['체이스', 'Chase'],
    ['트레버', 'Trevor'], ['브로디', 'Brody'], ['캘빈', 'Calvin'], ['트리스탄', 'Tristan'], ['브렌던', 'Brendan'],
    ['클리포드', 'Clifford'], ['하비', 'Harvey'], ['마커스', 'Marcus'], ['커티스', 'Curtis'], ['콘래드', 'Conrad'],
    ['댈러스', 'Dallas'], ['에밋', 'Emmett'], ['스펜서', 'Spencer'], ['롤런드', 'Roland'], ['홀든', 'Holden'],
    ['기디언', 'Gideon'], ['라이커', 'Ryker'], ['베켓', 'Beckett'],
    ['데이비드', 'David'], ['매슈', 'Matthew'], ['앤드류', 'Andrew'], ['크리스토퍼', 'Christopher'], ['토머스', 'Thomas'],
    ['에드워드', 'Edward'], ['로버트', 'Robert'], ['리처드', 'Richard'], ['애덤', 'Adam'], ['루크', 'Luke'],
    ['해리', 'Harry'], ['피터', 'Peter'], ['폴', 'Paul'], ['패트릭', 'Patrick'], ['스티븐', 'Stephen'],
    ['에이든', 'Aiden'], ['타일러', 'Tyler'], ['와이엇', 'Wyatt'], ['그레이슨', 'Grayson'], ['이스턴', 'Easton'],
    ['에즈라', 'Ezra'], ['재스퍼', 'Jasper'], ['줄리언', 'Julian'], ['레오', 'Leo'], ['도미닉', 'Dominic'],
    ['재비어', 'Xavier'], ['에이드리언', 'Adrian'], ['조나', 'Jonah'], ['애시턴', 'Ashton'], ['웨슬리', 'Wesley'],
    ['케빈', 'Kevin'], ['브라이언', 'Brian'], ['저스틴', 'Justin'], ['에릭', 'Eric'], ['카일', 'Kyle'],
    ['션', 'Sean'], ['이안', 'Ian'], ['앨런', 'Alan'], ['프랭크', 'Frank'], ['월터', 'Walter'],
    ['앨버트', 'Albert'], ['프레드릭', 'Frederick'], ['루퍼트', 'Rupert'], ['앨리스터', 'Alistair'], ['그레이엄', 'Graham'],
    ['레지널드', 'Reginald'], ['더스티', 'Dusty'], ['나이젤', 'Nigel'], ['마일로', 'Milo'], ['세드릭', 'Cedric'],
    ['로저', 'Roger'], ['프레이저', 'Fraser'], ['네드', 'Ned'], ['테오', 'Theo'], ['필립', 'Philip'],
    ['데이비', 'Davy'], ['가브리엘', 'Gabriel'], ['웨이드', 'Wade'], ['라파엘', 'Raphael'], ['루벤', 'Reuben'],
    ['셰인', 'Shane'], ['제프', 'Jeff'], ['시드', 'Sid'], ['앨빈', 'Alvin'], ['에드거', 'Edgar'],
    ['에이먼', 'Eamon'], ['엘리엇', 'Elliot'], ['제롬', 'Jerome'],
    ["일라이", "Eli"], ["리온", "Leon"], ["토비아스", "Tobias"], ["레이먼드", "Raymond"],
  ],
  female: [
    ['올리비아', 'Olivia'], ['엠마', 'Emma'], ['샬럿', 'Charlotte'], ['다이애나', 'Diana'], ['아멜리아', 'Amelia'],
    ['에이바', 'Ava'], ['소피아', 'Sophia'], ['이사벨라', 'Isabella'], ['미아', 'Mia'], ['에블린', 'Evelyn'],
    ['하퍼', 'Harper'], ['루나', 'Luna'], ['카밀라', 'Camila'], ['지안나', 'Gianna'], ['엘리자베스', 'Elizabeth'],
    ['엘리너', 'Eleanor'], ['엘라', 'Ella'], ['애비게일', 'Abigail'], ['스칼렛', 'Scarlett'], ['에밀리', 'Emily'],
    ['아리아', 'Aria'], ['페넬로페', 'Penelope'], ['클로이', 'Chloe'], ['레일라', 'Layla'], ['그웬', 'Gwen'],
    ['그웬돌린', 'Gwendolyn'], ['레베카', 'Rebecca'], ['레지나', 'Regina'], ['로레인', 'Lorraine'], ['엘리노어', 'Elinor'],
    ['릴리', 'Lily'], ['릴리안', 'Lillian'], ['릴리아나', 'Liliana'], ['마가렛', 'Margaret'], ['마릴린', 'Marilyn'],
    ['비비안', 'Vivian'], ['비앙카', 'Bianca'], ['사브리나', 'Sabrina'], ['사라', 'Sarah'], ['산드라', 'Sandra'],
    ['샤론', 'Sharon'], ['세이디', 'Sadie'], ['스테이시', 'Stacy'], ['에이프릴', 'April'], ['에반젤린', 'Evangeline'],
    ['이졸데', 'Isolde'], ['일레인', 'Elaine'], ['클라리스', 'Clarice'], ['트리샤', 'Tricia'], ['헤일리', 'Hailey'],
    ['헨리에타', 'Henrietta'], ['해리엇', 'Harriet'], ['헤이즐', 'Hazel'], ['프리실라', 'Priscilla'],
    ['오필리아', 'Ophelia'], ['세레나', 'Serena'], ['다프네', 'Daphne'], ['코델리아', 'Cordelia'], ['베로니카', 'Veronica'],
    ['시에나', 'Sienna'], ['매들린', 'Madeline'], ['멜로디', 'Melody'], ['바네사', 'Vanessa'], ['실비아', 'Sylvia'],
    ['조세핀', 'Josephine'], ['프레야', 'Freya'], ['셀레나', 'Selena'], ['나오미', 'Naomi'], ['에디스', 'Edith'],
    ['휘트니', 'Whitney'], ['로즈메리', 'Rosemary'], ['카르멘', 'Carmen'], ['베서니', 'Bethany'], ['로레타', 'Loretta'],
    ['제네비에브', 'Genevieve'], ['세라피나', 'Seraphina'], ['아라벨라', 'Arabella'], ['달리아', 'Dahlia'], ['펠리시티', 'Felicity'],
    ['잉그리드', 'Ingrid'], ['마야', 'Maya'], ['캐롤라인', 'Caroline'],
    ['그레이스', 'Grace'], ['해나', 'Hannah'], ['애나', 'Anna'], ['루시', 'Lucy'], ['앨리스', 'Alice'],
    ['조이', 'Zoe'], ['나탈리', 'Natalie'], ['레이첼', 'Rachel'], ['제시카', 'Jessica'], ['제니퍼', 'Jennifer'],
    ['애슐리', 'Ashley'], ['로런', 'Lauren'], ['메건', 'Megan'], ['에이미', 'Amy'], ['빅토리아', 'Victoria'],
    ['캐서린', 'Catherine'], ['헬렌', 'Helen'], ['로라', 'Laura'], ['메리', 'Mary'], ['앤', 'Anne'],
    ['제인', 'Jane'], ['소피', 'Sophie'], ['리디아', 'Lydia'], ['루비', 'Ruby'], ['몰리', 'Molly'],
    ['포피', 'Poppy'], ['데이지', 'Daisy'], ['바이올렛', 'Violet'], ['아이리스', 'Iris'], ['윌로', 'Willow'],
    ['오로라', 'Aurora'], ['노바', 'Nova'], ['페이지', 'Paige'], ['케일라', 'Kayla'], ['라일라', 'Lila'],
    ['테사', 'Tessa'], ['일라이자', 'Eliza'], ['세실리아', 'Cecilia'], ['애덜라인', 'Adeline'], ['마틸다', 'Matilda'],
    ['줄리엣', 'Juliet'], ['로즈', 'Rose'], ['헤더', 'Heather'], ['호프', 'Hope'], ['페이스', 'Faith'],
    ['라리사', 'Larissa'], ['테레사', 'Teresa'], ['록산느', 'Roxanne'], ['조앤', 'Joanne'], ['엘렌', 'Ellen'],
    ['로레나', 'Lorena'], ['보니', 'Bonnie'], ['모니카', 'Monica'], ['신시아', 'Cynthia'], ['아그네스', 'Agnes'],
    ['아드리아나', 'Adriana'], ['이브', 'Eve'], ['에바', 'Eva'], ['자스민', 'Jasmine'], ['카렌', 'Karen'],
    ['트레이시', 'Tracy'],
    ["애니", "Annie"], ["페이", "Faye"], ["로티", "Lottie"], ["라비니아", "Lavinia"], ["아이린", "Irene"],
    ["안젤라", "Angela"], ["조안", "Joan"], ["베티", "Betty"], ["케이트", "Kate"], ["케이틀린", "Caitlin"],
    ["힐다", "Hilda"],
  ],
  // 성별 구분 없이 쓰이는 이름
  unisex: [
    ['블레이크', 'Blake'], ['시드니', 'Sidney'], ['브라이어', 'Briar'], ['에이버리', 'Avery'], ['블레어', 'Blair'],
    ['프란시스', 'Francis'], ['샌디', 'Sandy'], ['할리', 'Harley'],
    ['로완', 'Rowan'], ['스카일러', 'Skyler'], ['리버', 'River'], ['케이시', 'Casey'], ['제이미', 'Jamie'],
    ['조던', 'Jordan'], ['다코타', 'Dakota'], ['리스', 'Reese'], ['로빈', 'Robin'], ['페이튼', 'Peyton'],
    ['켈시', 'Kelsey'],
    ["제시", "Jesse"], ["에머리", "Emery"],
  ],
};

window.PERSONA_DATA = {
  genders: [
    { id: 'female', ko: '여성', tag: 'girl' },
    { id: 'male', ko: '남성', tag: 'boy' },
    { id: 'nonbinary', ko: '논바이너리', tag: 'androgynous' },
  ],

  // order: east = 성+이름 / west = 이름+성, spaceKo = 한글 표기 시 띄어쓰기
  // 러시아처럼 성별에 따라 성이 바뀌면 { m: [...], f: [...] }
  // given.unisex: 성별과 상관없이 나오는 이름
  nations: {
    kr: {
      ko: '한국', region: 'asia', order: 'east', hanja: true, spaceKo: false,
      surnames: [
        ['김', 'Kim', '金'], ['이', 'Lee', '李'], ['박', 'Park', '朴'], ['최', 'Choi', '崔'], ['정', 'Jung', '鄭'],
        ['강', 'Kang', '姜'], ['윤', 'Yoon', '尹'], ['한', 'Han', '韓'], ['서', 'Seo', '徐'], ['신', 'Shin', '申'],
        ['조', 'Jo', '趙'], ['장', 'Jang', '張'], ['임', 'Lim', '林'], ['오', 'Oh', '吳'], ['권', 'Kwon', '權'],
        ['황', 'Hwang', '黃'], ['안', 'Ahn', '安'], ['송', 'Song', '宋'], ['전', 'Jeon', '全'], ['홍', 'Hong', '洪'],
        ['유', 'Yoo', '劉'], ['고', 'Ko', '高'], ['문', 'Moon', '文'], ['양', 'Yang', '梁'], ['손', 'Son', '孫'],
        ['배', 'Bae', '裵'], ['백', 'Baek', '白'], ['허', 'Heo', '許'], ['남', 'Nam', '南'], ['심', 'Shim', '沈'],
        ['류', 'Ryu', '柳'], ['노', 'Noh', '盧'], ['하', 'Ha', '河'], ['곽', 'Kwak', '郭'], ['성', 'Sung', '成'],
        ['차', 'Cha', '車'], ['구', 'Koo', '具'], ['우', 'Woo', '禹'], ['주', 'Joo', '朱'], ['나', 'Na', '羅'],
        ['민', 'Min', '閔'], ['진', 'Jin', '陳'], ['지', 'Ji', '池'], ['엄', 'Eom', '嚴'], ['채', 'Chae', '蔡'],
        ['원', 'Won', '元'], ['천', 'Cheon', '千'], ['방', 'Bang', '方'], ['공', 'Kong', '孔'], ['현', 'Hyun', '玄'],
      ],
      given: {
        female: [
          ['서연', 'Seoyeon', '瑞妍'], ['하윤', 'Hayoon', '夏潤'], ['은채', 'Eunchae', '恩彩'], ['수아', 'Sua', '秀雅'], ['다인', 'Dain', '多仁'],
          ['예린', 'Yerin', '藝潾'], ['채원', 'Chaewon', '彩媛'], ['소희', 'Sohee', '素熙'], ['서윤', 'Seoyoon', '瑞允'], ['서현', 'Seohyun', '瑞賢'],
          ['하은', 'Haeun', '夏恩'], ['민서', 'Minseo', '旼序'], ['윤서', 'Yoonseo', '允瑞'], ['지아', 'Jia', '智雅'], ['다은', 'Daeun', '多恩'],
          ['은지', 'Eunji', '恩智'], ['지윤', 'Jiyoon', '智允'], ['예은', 'Yeeun', '藝恩'], ['소민', 'Somin', '素旼'], ['아인', 'Ain', '雅仁'],
          ['시은', 'Sieun', '始恩'], ['가은', 'Gaeun', '佳恩'], ['유나', 'Yuna', '裕娜'], ['서영', 'Seoyoung', '瑞英'], ['민지', 'Minji', '旼智'],
          ['수민', 'Sumin', '秀旼'], ['아란', 'Aran', '雅蘭'], ['채영', 'Chaeyoung', '彩英'], ['혜원', 'Hyewon', '惠媛'], ['유정', 'Yujeong', '裕貞'],
          ['로아', 'Roa'], ['리아', 'Ria'], ['아윤', 'Ayoon', '雅潤'], ['하린', 'Harin', '夏潾'], ['나윤', 'Nayoon', '娜潤'],
          ['시현', 'Sihyun', '始賢'], ['다미', 'Dami', '多美'], ['서아', 'Seoa', '瑞雅'], ['수연', 'Suyeon', '秀妍'], ['소율', 'Soyul', '素律'],
          ['설아', 'Seola', '雪雅'], ['나은', 'Naeun', '娜恩'], ['윤아', 'Yoona', '允雅'], ['다희', 'Dahee', '多熙'], ['태희', 'Taehee', '泰熙'],
          ['은별', 'Eunbyeol'], ['아라', 'Ara'], ['예원', 'Yewon', '藝媛'], ['예림', 'Yerim', '藝林'], ['예솔', 'Yesol'],
          ['영은', 'Youngeun', '英恩'], ['예빈', 'Yebin', '藝彬'], ['지유', 'Jiyu', '智柔'], ['아진', 'Ajin', '雅珍'], ['연주', 'Yeonju', '姸珠'],
          ['하나', 'Hana'], ['세연', 'Seyeon', '世姸'], ['유연', 'Yuyeon', '柔姸'], ['소윤', 'Soyoon', '素允'], ['은하', 'Eunha', '銀河'],
          ['은서', 'Eunseo', '恩瑞'], ['세라', 'Sera', '世羅'], ['주희', 'Joohee', '珠熙'], ['혜영', 'Hyeyoung', '惠英'], ['윤영', 'Yoonyoung', '允英'],
          ['선영', 'Sunyoung', '善英'],
        ],
        male: [
          ['도윤', 'Doyoon', '道允'], ['시우', 'Siwoo', '時宇'], ['준혁', 'Junhyuk', '俊赫'], ['태오', 'Taeo', '泰旿'], ['현우', 'Hyunwoo', '賢宇'],
          ['재민', 'Jaemin', '在旻'], ['승현', 'Seunghyun', '承賢'], ['민재', 'Minjae', '旻載'], ['건우', 'Gunwoo', '建宇'], ['민준', 'Minjun', '旻俊'],
          ['서준', 'Seojun', '瑞俊'], ['예준', 'Yejun', '藝俊'], ['하준', 'Hajun', '夏俊'], ['지호', 'Jiho', '智浩'], ['주원', 'Juwon', '周元'],
          ['우진', 'Woojin', '宇鎭'], ['선우', 'Sunwoo', '善宇'], ['지훈', 'Jihoon', '志勳'], ['은우', 'Eunwoo', '恩宇'], ['정우', 'Jungwoo', '正宇'],
          ['승우', 'Seungwoo', '承佑'], ['지환', 'Jihwan', '智煥'], ['태현', 'Taehyun', '泰賢'], ['진우', 'Jinwoo', '振宇'], ['민석', 'Minseok', '旻錫'],
          ['도현', 'Dohyun', '道賢'], ['동현', 'Donghyun', '東賢'], ['재윤', 'Jaeyoon', '在允'], ['이준', 'Ijun', '利俊'], ['로운', 'Roun'],
          ['수호', 'Suho', '守護'], ['유찬', 'Yuchan', '裕燦'], ['도훈', 'Dohoon', '道勳'], ['시안', 'Sian', '時安'], ['정훈', 'Junghoon', '正勳'],
          ['성민', 'Sungmin', '成旻'], ['윤호', 'Yoonho', '允浩'], ['승민', 'Seungmin', '承旻'], ['재현', 'Jaehyun', '在賢'], ['준호', 'Junho', '俊浩'],
          ['성현', 'Sunghyun', '聖賢'], ['진혁', 'Jinhyuk', '振赫'], ['준서', 'Junseo', '俊瑞'], ['건희', 'Gunhee', '建熙'], ['태윤', 'Taeyoon', '泰允'],
          ['민호', 'Minho', '旻浩'], ['도운', 'Doun', '道雲'], ['기범', 'Kibum', '基範'], ['상현', 'Sanghyun', '相賢'], ['민우', 'Minwoo', '旻宇'],
          ['태양', 'Taeyang', '太陽'], ['우혁', 'Woohyuk', '宇赫'],
        ],
        unisex: [
          ['지우', 'Jiwoo', '智友'], ['유진', 'Yujin', '有眞'], ['이안', 'Ian', '利安'], ['수빈', 'Subin', '秀彬'], ['지민', 'Jimin', '智旻'],
          ['연우', 'Yeonwoo', '然宇'], ['시윤', 'Siyoon', '詩允'], ['아람', 'Aram'], ['유하', 'Yuha', '柔河'], ['지안', 'Jian', '智安'],
          ['하람', 'Haram'], ['이솔', 'Isol'], ['바다', 'Bada'], ['시우', 'Siwoo', '時宇'], ['노을', 'Noeul'],
          ['지원', 'Jiwon', '志遠'], ['루다', 'Ruda'], ['이레', 'Ire'], ['시원', 'Siwon', '始元'], ['다온', 'Daon'],
          ['새론', 'Saeron'], ['유원', 'Yuwon', '裕元'], ['정우', 'Jungwoo', '正宇'], ['가온', 'Gaon'], ['연희', 'Yeonhee', '姸熙'],
          ['한솔', 'Hansol'], ['예담', 'Yedam'], ['은호', 'Eunho', '恩浩'], ['은성', 'Eunseong', '恩星'], ['보람', 'Boram'],
          ['여름', 'Yeoreum'], ['가을', 'Gaeul'], ['세림', 'Serim', '世林'], ['주영', 'Jooyoung', '珠英'], ['유빈', 'Yubin', '有彬'],
          ['도희', 'Dohee', '道熙'], ['수현', 'Soohyun', '秀賢'], ['소리', 'Sori'], ['윤서', 'Yoonseo', '允瑞'], ['아현', 'Ahyun', '雅賢'],
          ['수인', 'Suin', '秀仁'], ['세현', 'Sehyun', '世賢'], ['진솔', 'Jinsol', '眞率'], ['다인', 'Dain', '多仁'], ['유민', 'Yumin', '有旻'],
          ['소희', 'Sohee', '素熙'], ['재림', 'Jaerim', '在林'], ['해경', 'Haekyung', '海景'], ['노아', 'Noa'], ['하경', 'Hakyung', '夏景'],
          ['이채', 'Ichae', '異彩'], ['온', 'On'], ['현', 'Hyun', '賢'], ['봄', 'Bom'], ['유', 'Yu', '柔'],
          ['윤', 'Yoon', '允'], ['솔', 'Sol'], ['휘', 'Hwi', '輝'], ['겸', 'Gyeom', '謙'], ['환', 'Hwan', '煥'],
          ['재희', 'Jaehee', '在熙'], ['해인', 'Haein', '海仁'], ['다빈', 'Dabin', '多彬'], ['지현', 'Jihyun', '智賢'],
        ],
      },
    },
    jp: {
      ko: '일본', region: 'asia', order: 'east', hanja: true, hanjaSpace: true, spaceKo: true,
      surnames: [
        ['사토', 'Sato', '佐藤'], ['스즈키', 'Suzuki', '鈴木'], ['타카하시', 'Takahashi', '高橋'], ['이치노세', 'Ichinose', '一ノ瀬'], ['키리시마', 'Kirishima', '霧島'],
        ['시노미야', 'Shinomiya', '四宮'], ['아마미야', 'Amamiya', '雨宮'], ['쿠로사와', 'Kurosawa', '黒沢'], ['타나카', 'Tanaka', '田中'], ['이토', 'Ito', '伊藤'],
        ['와타나베', 'Watanabe', '渡辺'], ['야마모토', 'Yamamoto', '山本'], ['나카무라', 'Nakamura', '中村'], ['코바야시', 'Kobayashi', '小林'], ['카토', 'Kato', '加藤'],
        ['요시다', 'Yoshida', '吉田'], ['야마다', 'Yamada', '山田'], ['사사키', 'Sasaki', '佐々木'], ['야마구치', 'Yamaguchi', '山口'], ['사이토', 'Saito', '斎藤'],
        ['마츠모토', 'Matsumoto', '松本'], ['이노우에', 'Inoue', '井上'], ['키무라', 'Kimura', '木村'], ['하야시', 'Hayashi', '林'], ['시미즈', 'Shimizu', '清水'],
        ['야마자키', 'Yamazaki', '山崎'], ['모리', 'Mori', '森'], ['이케다', 'Ikeda', '池田'], ['하시모토', 'Hashimoto', '橋本'], ['호시노', 'Hoshino', '星野'],
        ['미야모토', 'Miyamoto', '宮本'], ['쿠로다', 'Kuroda', '黒田'], ['이시카와', 'Ishikawa', '石川'], ['나카지마', 'Nakajima', '中島'], ['오가와', 'Ogawa', '小川'],
        ['아사히나', 'Asahina', '朝比奈'], ['오오하라', 'Ohara', '大原'], ['이시타니', 'Ishitani', '石谷'], ['이와사키', 'Iwasaki', '岩崎'], ['하야시바라', 'Hayashibara', '林原'],
        ['이마이', 'Imai', '今井'], ['시라카와', 'Shirakawa', '白川'], ['사사하라', 'Sasahara', '笹原'], ['카와사키', 'Kawasaki', '川崎'], ['나카하라', 'Nakahara', '中原'],
        ['니시나', 'Nishina', '仁科'], ['하세가와', 'Hasegawa', '長谷川'], ['하나조노', 'Hanazono', '花園'], ['히라이', 'Hirai', '平井'], ['시노다', 'Shinoda', '篠田'],
        ['아이자와', 'Aizawa', '相沢'], ['야다', 'Yada', '矢田'], ['후루야', 'Furuya', '古谷'], ['모리야마', 'Moriyama', '森山'], ['이리에', 'Irie', '入江'],
        ['나라', 'Nara', '奈良'], ['시이나', 'Shiina', '椎名'], ['미야와키', 'Miyawaki', '宮脇'], ['마츠이', 'Matsui', '松井'], ['사쿠라이', 'Sakurai', '桜井'],
      ],
      given: {
        female: [
          ['하루카', 'Haruka', '遥'], ['유이', 'Yui', '結衣'], ['린', 'Rin', '凛'], ['사쿠라', 'Sakura', '桜'], ['미오', 'Mio', '美桜'],
          ['츠바키', 'Tsubaki', '椿'], ['시오리', 'Shiori', '栞'], ['히나', 'Hina', '陽菜'], ['리오', 'Rio', '莉緒'], ['메이', 'Mei', '芽依'],
          ['이치카', 'Ichika', '一花'], ['아카리', 'Akari', '朱里'], ['미사키', 'Misaki', '美咲'], ['칸나', 'Kanna', '環奈'], ['모모카', 'Momoka', '桃花'],
          ['나나미', 'Nanami', '七海'], ['시즈쿠', 'Shizuku', '雫'], ['루나', 'Runa', '瑠菜'], ['미유', 'Miyu', '美優'], ['코코네', 'Kokone', '心音'],
          ['호노카', 'Honoka', '穂乃果'], ['하나', 'Hana', '花'], ['히마리', 'Himari', '陽葵'], ['리코', 'Riko', '莉子'], ['나나', 'Nana', '奈々'],
          ['카논', 'Kanon', '花音'], ['코토네', 'Kotone', '琴音'], ['유즈키', 'Yuzuki', '柚月'], ['히요리', 'Hiyori', '日和'], ['아이리', 'Airi', '愛莉'],
          ['유우카', 'Yuuka', '優花'], ['안', 'An', '杏'], ['나츠미', 'Natsumi', '夏美'], ['카스미', 'Kasumi', '霞'], ['후우카', 'Fuuka', '風花'],
          ['아야노', 'Ayano', '綾乃'], ['미츠요', 'Mitsuyo', '光代'], ['카즈하', 'Kazuha', '和葉'], ['마오', 'Mao', '真央'], ['시호', 'Shiho', '志保'],
          ['마호', 'Maho', '真帆'], ['카나', 'Kana', '佳奈'], ['코코로', 'Kokoro', '心'], ['나노카', 'Nanoka', '菜乃花'], ['나코', 'Nako', '奈子'],
          ['마후유', 'Mafuyu', '真冬'], ['사키', 'Saki', '咲'], ['미라이', 'Mirai', '未来'], ['사나에', 'Sanae', '早苗'], ['사아야', 'Saaya', '紗綾'],
          ['카호', 'Kaho', '果歩'], ['아야카', 'Ayaka', '彩花'], ['아즈사', 'Azusa', '梓'], ['안즈', 'Anzu', '杏珠'], ['미유키', 'Miyuki', '美幸'],
        ],
        male: [
          ['하루토', 'Haruto', '陽翔'], ['렌', 'Ren', '蓮'], ['소마', 'Soma', '颯真'], ['카이토', 'Kaito', '海斗'], ['료', 'Ryo', '涼'],
          ['이츠키', 'Itsuki', '樹'], ['미나토', 'Minato', '湊'], ['유마', 'Yuma', '悠真'], ['소타', 'Sota', '蒼太'], ['리쿠', 'Riku', '陸'],
          ['유토', 'Yuto', '悠斗'], ['쇼', 'Sho', '翔'], ['타쿠미', 'Takumi', '拓海'], ['다이키', 'Daiki', '大輝'], ['류노스케', 'Ryunosuke', '龍之介'],
          ['켄지', 'Kenji', '健二'], ['다이스케', 'Daisuke', '大輔'], ['토오루', 'Tohru', '透'], ['다이치', 'Daichi', '大地'], ['코우시', 'Koushi', '光志'],
          ['케이지', 'Keiji', '啓二'], ['타쿠야', 'Takuya', '拓也'], ['테츠야', 'Tetsuya', '哲也'], ['이치로', 'Ichiro', '一郎'], ['히로시', 'Hiroshi', '博'],
          ['에이타', 'Eita', '瑛太'], ['소우', 'Sou', '蒼'], ['토모야', 'Tomoya', '智也'], ['쿄헤이', 'Kyohei', '恭平'], ['켄타', 'Kenta', '健太'],
          ['레이지', 'Reiji', '玲司'], ['료마', 'Ryoma', '亮真'], ['미노루', 'Minoru', '実'], ['슈야', 'Shuya', '修也'],
        ],
        unisex: [
          ['히나타', 'Hinata', '陽向'], ['아키라', 'Akira', '明'], ['소라', 'Sora', '空'], ['유키', 'Yuki', '雪'], ['카에데', 'Kaede', '楓'],
          ['마코토', 'Makoto', '誠'], ['시온', 'Shion', '紫苑'], ['아오이', 'Aoi', '葵'], ['미즈키', 'Mizuki', '瑞希'], ['하루', 'Haru', '春'],
          ['히카리', 'Hikari', '光'], ['유우', 'Yuu', '優'], ['리츠', 'Ritsu', '律'], ['니키', 'Niki', '仁希'], ['아유무', 'Ayumu', '歩'],
          ['아마네', 'Amane', '天音'],
        ],
      },
    },
    cn: {
      ko: '중국', region: 'asia', order: 'east', sinoRead: true, hanja: true, spaceKo: true,
      surnames: [
        ['왕', 'Wang', '王'], ['리', 'Li', '李'], ['장', 'Zhang', '张'], ['천', 'Chen', '陈'], ['린', 'Lin', '林'],
        ['선', 'Shen', '沈'], ['셰', 'Xie', '谢'], ['루', 'Lu', '陆'], ['류', 'Liu', '刘'], ['양', 'Yang', '杨'],
        ['자오', 'Zhao', '赵'], ['황', 'Huang', '黄'], ['저우', 'Zhou', '周'], ['우', 'Wu', '吴'], ['쉬', 'Xu', '徐'],
        ['쑨', 'Sun', '孙'], ['마', 'Ma', '马'], ['주', 'Zhu', '朱'], ['후', 'Hu', '胡'], ['궈', 'Guo', '郭'],
        ['허', 'He', '何'], ['가오', 'Gao', '高'], ['뤄', 'Luo', '罗'], ['정', 'Zheng', '郑'], ['량', 'Liang', '梁'],
        ['탕', 'Tang', '唐'],
        ["한", "Han", "韩"], ["펑", "Peng", "彭"], ["둥", "Dong", "董"], ["차오", "Cao", "曹"],
        ["위안", "Yuan", "袁"], ["덩", "Deng", "邓"], ["푸", "Fu", "傅"], ["쩡", "Zeng", "曾"],
        ["뤼", "Lyu", "吕"], ["쑤", "Su", "苏"], ["장", "Jiang", "蒋"], ["차이", "Cai", "蔡"],
        ["딩", "Ding", "丁"], ["웨이", "Wei", "魏"], ["쉐", "Xue", "薛"], ["예", "Ye", "叶"],
        ["위", "Yu", "余"], ["두", "Du", "杜"], ["다이", "Dai", "戴"], ["샤", "Xia", "夏"],
        ["중", "Zhong", "钟"], ["톈", "Tian", "田"], ["런", "Ren", "任"], ["판", "Fan", "范"],
        ["팡", "Fang", "方"], ["스", "Shi", "石"], ["야오", "Yao", "姚"], ["탄", "Tan", "谭"],
        ["랴오", "Liao", "廖"], ["쩌우", "Zou", "邹"], ["슝", "Xiong", "熊"], ["진", "Jin", "金"],
        ["하오", "Hao", "郝"], ["쿵", "Kong", "孔"], ["바이", "Bai", "白"], ["추이", "Cui", "崔"],
        ["캉", "Kang", "康"], ["친", "Qin", "秦"], ["구", "Gu", "顾"], ["허우", "Hou", "侯"],
        ["사오", "Shao", "邵"], ["멍", "Meng", "孟"], ["룽", "Long", "龙"], ["돤", "Duan", "段"],
        ["레이", "Lei", "雷"], ["첸", "Qian", "钱"], ["인", "Yin", "尹"], ["창", "Chang", "常"],
        ["라이", "Lai", "赖"], ["원", "Wen", "文"],
      ],
      given: {
        female: [
          ['위란', 'Yulan', '玉兰'], ['샤오위', 'Xiaoyu', '晓雨'], ['링링', 'Lingling', '玲玲'], ['메이', 'Mei', '梅'], ['칭옌', 'Qingyan', '清妍'],
          ['멍야오', 'Mengyao', '梦瑶'], ['쯔한', 'Zihan', '子涵'], ['신이', 'Xinyi', '欣怡'], ['이눠', 'Yinuo', '一诺'], ['신옌', 'Xinyan', '欣妍'],
          ['위퉁', 'Yutong', '雨桐'], ['자이', 'Jiayi', '佳怡'], ['위팅', 'Yuting', '雨婷'], ['신위에', 'Xinyue', '欣悦'], ['위치', 'Yuqi', '雨琪'],
          ['멍치', 'Mengqi', '梦琪'], ['쯔옌', 'Ziyan', '紫嫣'], ['뤄시', 'Ruoxi', '若曦'], ['자위에', 'Jiayue', '佳悦'], ['쓰위', 'Siyu', '思雨'],
          ['커신', 'Kexin', '可欣'], ['시위에', 'Xiyue', '希玥'], ['징이', 'Jingyi', '静怡'], ['위멍', 'Yumeng', '雨萌'], ['스한', 'Shihan', '诗涵'],
          ['쯔팅', 'Ziting', '梓婷'],
          ["팅팅", "Tingting", "婷婷"], ["야치", "Yaqi", "雅琪"], ["후이민", "Huimin", "慧敏"], ["자닝", "Jianing", "佳宁"],
          ["위신", "Yuxin", "雨欣"], ["멍제", "Mengjie", "梦洁"], ["쓰치", "Siqi", "思琪"], ["천시", "Chenxi", "晨曦"],
          ["완칭", "Wanqing", "婉清"], ["위옌", "Yuyan", "语嫣"], ["뤄한", "Ruohan", "若涵"], ["쯔린", "Zilin", "紫琳"],
          ["야징", "Yajing", "雅静"], ["무칭", "Muqing", "沐晴"], ["이이", "Yiyi", "依依"], ["페이산", "Peishan", "佩珊"],
          ["슈야오", "Shuyao", "舒窈"], ["차이웨이", "Caiwei", "采薇"], ["슈잉", "Xiuying", "秀英"], ["리화", "Lihua", "丽华"],
          ["수펀", "Shufen", "淑芬"], ["구이란", "Guilan", "桂兰"], ["위메이", "Yumei", "玉梅"], ["린", "Lin", "琳"],
          ["옌", "Yan", "燕"], ["룽", "Rong", "蓉"], ["쉐", "Xue", "雪"], ["칭", "Qing", "晴"],
          ["웨", "Yue", "月"], ["웨이", "Wei", "薇"], ["란", "Lan", "岚"], ["팅", "Ting", "婷"],
        ],
        male: [
          ['하오란', 'Haoran', '浩然'], ['쯔쉬안', 'Zixuan', '子轩'], ['이천', 'Yichen', '奕辰'], ['쥔제', 'Junjie', '俊杰'], ['무바이', 'Mubai', '慕白'],
          ['윈셴', 'Yunxian', '云贤'], ['톈유', 'Tianyou', '天佑'], ['자오양', 'Zhaoyang', '朝阳'], ['위쩌', 'Yuze', '宇泽'], ['쯔루이', 'Zirui', '梓睿'],
          ['하오위', 'Haoyu', '浩宇'], ['보원', 'Bowen', '博文'], ['밍제', 'Mingjie', '明杰'], ['쯔천', 'Zichen', '梓晨'], ['젠위', 'Jianyu', '健宇'],
          ['신하오', 'Xinhao', '欣浩'], ['루이린', 'Ruilin', '瑞霖'], ['위항', 'Yuhang', '宇航'], ['자청', 'Jiacheng', '嘉诚'], ['쩌위', 'Zeyu', '泽宇'],
          ['위샹', 'Yuxiang', '宇翔'], ['웨이쩌', 'Weize', '伟泽'], ['쥔시', 'Junxi', '俊熙'], ['위보', 'Yubo', '宇博'], ['하오쉬안', 'Haoxuan', '浩轩'],
          ['즈위안', 'Zhiyuan', '致远'], ['징쩌', 'Jingze', '景泽'], ['무천', 'Muchen', '沐宸'],
          ["위쉬안", "Yuxuan", "宇轩"], ["쯔모", "Zimo", "子墨"], ["징밍", "Jingming", "景明"], ["청위", "Chengyu", "承宇"],
          ["이판", "Yifan", "亦凡"], ["이페이", "Yifei", "逸飞"], ["슈원", "Xiuwen", "修文"], ["쥔하오", "Junhao", "君昊"],
          ["톈레이", "Tianlei", "天磊"], ["위천", "Yuchen", "昱辰"], ["즈싱", "Zhixing", "知行"], ["원저", "Wenzhe", "文哲"],
          ["하오위안", "Haoyuan", "浩远"], ["즈창", "Zhiqiang", "志强"], ["젠궈", "Jianguo", "建国"], ["궈창", "Guoqiang", "国强"],
          ["전화", "Zhenhua", "振华"], ["슈밍", "Shuming", "树明"], ["웨이", "Wei", "伟"], ["레이", "Lei", "磊"],
          ["펑", "Peng", "鹏"], ["타오", "Tao", "涛"], ["쥔", "Jun", "军"], ["창", "Qiang", "强"],
          ["융", "Yong", "勇"], ["제", "Jie", "杰"], ["하오", "Hao", "浩"], ["루이", "Rui", "睿"],
          ["쩌", "Ze", "泽"], ["천", "Chen", "琛"], ["카이", "Kai", "凯"],
        ],
        unisex: [
          ['쯔한', 'Zihan', '子涵'], ['위한', 'Yuhan', '雨涵'], ['이쉬안', 'Yixuan', '亦轩'],
          ["천", "Chen", "辰"], ["안", "An", "安"], ["러", "Le", "乐"], ["뤄", "Luo", "洛"],
          ["위안", "Yuan", "远"], ["자", "Jia", "佳"], ["쓰위안", "Siyuan", "思远"], ["원이", "Wenyi", "文一"],
          ["즈칭", "Zhiqing", "知青"], ["이닝", "Yining", "怡宁"],
        ],
      },
    },
    // ---- 아래 나라들은 이름 목록을 다른 나라와 공유 (shares) ----
    // trad: 한자를 번체자로 / surnameRoman: 성의 로마자·한글 표기 교체 [한자] → [한글, 로마자]
    tw: {
      ko: '대만', region: 'asia', shares: ['cn'], sinoRead: true, trad: true,
      surnameRoman: {
        張: ['장', 'Chang'], 陳: ['천', 'Chen'], 李: ['리', 'Lee'], 周: ['저우', 'Chou'], 徐: ['쉬', 'Hsu'],
        謝: ['셰', 'Hsieh'], 趙: ['자오', 'Chao'], 鄭: ['정', 'Cheng'], 郭: ['궈', 'Kuo'], 何: ['허', 'Ho'],
        高: ['가오', 'Kao'], 羅: ['뤄', 'Lo'], 朱: ['주', 'Chu'], 劉: ['류', 'Liu'], 黃: ['황', 'Huang'],
      },
    },
    hk: {
      ko: '홍콩', region: 'asia', shares: ['cn'], sinoRead: true, trad: true,
      // 절반은 영어 이름 + 성 (예: 제이슨 웡)
      englishGiven: { from: ['us', 'uk'], rate: 0.5 },
      surnameRoman: {
        王: ['웡', 'Wong'], 李: ['리', 'Lee'], 張: ['청', 'Cheung'], 陳: ['찬', 'Chan'], 林: ['람', 'Lam'],
        沈: ['삼', 'Shum'], 謝: ['체', 'Tse'], 陸: ['룩', 'Luk'], 劉: ['라우', 'Lau'], 楊: ['영', 'Yeung'],
        趙: ['치우', 'Chiu'], 黃: ['웡', 'Wong'], 周: ['차우', 'Chow'], 吳: ['응', 'Ng'], 徐: ['초이', 'Tsui'],
        孫: ['쉰', 'Suen'], 馬: ['마', 'Ma'], 朱: ['추', 'Chu'], 胡: ['우', 'Wu'], 郭: ['궉', 'Kwok'],
        何: ['호', 'Ho'], 高: ['코', 'Ko'], 羅: ['로', 'Law'], 鄭: ['쳉', 'Cheng'], 梁: ['렁', 'Leung'], 唐: ['통', 'Tong'],
        韓: ['혼', 'Hon'], 彭: ['팡', 'Pang'], 董: ['퉁', 'Tung'], 曹: ['초우', 'Cho'], 袁: ['윤', 'Yuen'],
        鄧: ['탕', 'Tang'], 傅: ['푸', 'Fu'], 曾: ['창', 'Tsang'], 呂: ['뢰', 'Lui'], 蘇: ['소우', 'So'],
        蔣: ['청', 'Tseung'], 蔡: ['초이', 'Choi'], 丁: ['딩', 'Ting'], 魏: ['응아이', 'Ngai'], 薛: ['싯', 'Sit'],
        葉: ['입', 'Ip'], 余: ['위', 'Yu'], 杜: ['토', 'To'], 戴: ['다이', 'Tai'], 夏: ['하', 'Ha'],
        鍾: ['청', 'Chung'], 田: ['틴', 'Tin'], 任: ['얌', 'Yam'], 范: ['판', 'Fan'], 方: ['퐁', 'Fong'],
        石: ['섹', 'Shek'], 姚: ['이우', 'Yiu'], 譚: ['탐', 'Tam'], 廖: ['리우', 'Liu'], 鄒: ['차우', 'Chau'],
        熊: ['훙', 'Hung'], 金: ['캄', 'Kam'], 郝: ['콕', 'Kok'], 孔: ['훙', 'Hung'], 白: ['박', 'Pak'],
        崔: ['초이', 'Choi'], 康: ['홍', 'Hong'], 秦: ['천', 'Chun'], 顧: ['구', 'Ku'], 侯: ['하우', 'Hau'],
        邵: ['시우', 'Siu'], 孟: ['망', 'Mang'], 龍: ['룽', 'Lung'], 段: ['뒨', 'Tuen'], 雷: ['뢰', 'Lui'],
        錢: ['친', 'Chin'], 尹: ['완', 'Wan'], 常: ['성', 'Sheung'], 賴: ['라이', 'Lai'], 文: ['만', 'Man'],
      },
    },
    us: {
      ko: '미국', region: 'americas', order: 'west',
      // 하위 그룹: rate 확률로 성·이름을 모두 from 나라 목록에서 뽑고, 국적은 '{label} 미국인'으로 표기 (surnames 는 추가 성)
      subgroups: [{ label: '히스패닉계', from: 'es', rate: 0.15 }],
      surnames: [
        ['포스터', 'Foster'], ['헤이스', 'Hayes'], ['브룩스', 'Brooks'], ['칼라일', 'Carlisle'], ['리드', 'Reed'],
        ['모건', 'Morgan'], ['설리번', 'Sullivan'], ['코너', 'Connor'], ...ANGLO.surnames,
      ],
      given: {
        female: [
          ['엘리너', 'Eleanor'], ['매디슨', 'Madison'], ['헤일리', 'Hailey'], ['오드리', 'Audrey'], ['클레어', 'Claire'],
          ['줄리아', 'Julia'], ['스텔라', 'Stella'], ['노라', 'Nora'], ...ANGLO.female,
        ],
        male: [
          ['이선', 'Ethan'], ['노아', 'Noah'], ['케일럽', 'Caleb'], ['라이언', 'Ryan'], ['오웬', 'Owen'],
          ['잭슨', 'Jackson'], ['루카스', 'Lucas'], ['네이선', 'Nathan'], ...ANGLO.male,
        ],
        unisex: [
          ...ANGLO.unisex,
        ],
      },
    },
    uk: {
      ko: '영국', region: 'europe', order: 'west',
      surnames: [
        ['애쉬포드', 'Ashford'], ['블랙우드', 'Blackwood'], ['해링턴', 'Harrington'], ['윈슬로', 'Winslow'], ['펨브로크', 'Pembroke'],
        ['크롬웰', 'Cromwell'], ['헤이스팅스', 'Hastings'], ['에버렛', 'Everett'], ...ANGLO.surnames,
      ],
      given: {
        female: [
          ['비어트리스', 'Beatrice'], ['이모젠', 'Imogen'], ['샬럿', 'Charlotte'], ['플로렌스', 'Florence'], ['로절린드', 'Rosalind'],
          ['엘로이즈', 'Eloise'], ['헨리에타', 'Henrietta'], ['아이비', 'Ivy'], ...ANGLO.female,
        ],
        male: [
          ['시어도어', 'Theodore'], ['에드먼드', 'Edmund'], ['아서', 'Arthur'], ['세바스찬', 'Sebastian'], ['올리버', 'Oliver'],
          ['제임스', 'James'], ['퍼시벌', 'Percival'], ['휴고', 'Hugo'], ...ANGLO.male,
        ],
        unisex: [
          ...ANGLO.unisex,
        ],
      },
    },
    ca: {
      ko: '캐나다', region: 'americas', shares: ['us', 'uk'],
      subgroups: [{
        label: '프랑스계', from: 'fr', rate: 0.2, // 퀘벡
        surnames: [
        ['트랑블레', 'Tremblay'], ['가뇽', 'Gagnon'], ['루아', 'Roy'], ['코테', 'Côté'], ['부샤르', 'Bouchard'],
        ['고티에', 'Gauthier'], ['모랭', 'Morin'], ['라부아', 'Lavoie'], ['포르탱', 'Fortin'], ['가녜', 'Gagné'],
        ['우엘레', 'Ouellet'], ['펠티에', 'Pelletier'], ['벨랑제', 'Bélanger'], ['레베스크', 'Lévesque'],
      ],
      }],
    },
    au: { ko: '호주', region: 'oceania', shares: ['uk', 'us'] },
    nz: { ko: '뉴질랜드', region: 'oceania', shares: ['uk', 'us'] },
    mx: { ko: '멕시코', region: 'americas', shares: ['es'] },
    ar: { ko: '아르헨티나', region: 'americas', shares: ['es', 'it'] },
    cl: { ko: '칠레', region: 'americas', shares: ['es'] },
    ie: {
      ko: '아일랜드', region: 'europe', shares: ['uk'],
      // 영국 목록 + 아일랜드 고유 이름 (rate: 고유 목록에서만 뽑을 확률)
      extra: {
        rate: 0.6,
        surnames: [
        ["머피", "Murphy"], ["켈리", "Kelly"], ["오설리번", "O'Sullivan"], ["월시", "Walsh"], ["번", "Byrne"],
        ["도일", "Doyle"], ["매카시", "McCarthy"], ["갤러거", "Gallagher"], ["도허티", "Doherty"], ["케네디", "Kennedy"],
        ["린치", "Lynch"], ["머리", "Murray"], ["맥러플린", "McLoughlin"], ["브레넌", "Brennan"], ["피츠제럴드", "Fitzgerald"],
        ["놀런", "Nolan"], ["패럴", "Farrell"], ["킨", "Keane"], ["브린", "Breen"], ["맥그래스", "McGrath"],
      ],
        given: {
          female: [
          ["이퍼", "Aoife"], ["시어셔", "Saoirse"], ["니브", "Niamh"], ["시번", "Siobhán"], ["키바", "Caoimhe"],
          ["로신", "Róisín"], ["클로다", "Clodagh"], ["올라", "Orla"], ["애슐링", "Aisling"], ["키아라", "Ciara"],
          ["시네이드", "Sinéad"], ["그러니아", "Gráinne"], ["메이브", "Maeve"],
        ],
          male: [
          ["숀", "Seán"], ["키언", "Cian"], ["어신", "Oisín"], ["코너", "Conor"], ["대러", "Darragh"],
          ["핀", "Finn"], ["타이그", "Tadhg"], ["킬리언", "Cillian"], ["로넌", "Ronan"], ["데클런", "Declan"],
          ["오언", "Eoin"], ["나일", "Niall"], ["퍼드릭", "Pádraig"], ["코맥", "Cormac"],
        ],
        },
      },
    },
    fr: {
      ko: '프랑스', region: 'europe', order: 'west',
      surnames: [
        ['뒤부아', 'Dubois'], ['르페브르', 'Lefèvre'], ['모로', 'Moreau'], ['로랑', 'Laurent'], ['베르나르', 'Bernard'],
        ['퐁텐', 'Fontaine'], ['지라르', 'Girard'], ['드 라 쿠르', 'de la Cour'], ['마르탱', 'Martin'], ['르나르', 'Renard'],
        ['토마', 'Thomas'], ['프티', 'Petit'], ['로베르', 'Robert'], ['리샤르', 'Richard'], ['뒤랑', 'Durand'],
        ['시몽', 'Simon'], ['미셸', 'Michel'], ['르루아', 'Leroy'], ['루', 'Roux'], ['베르트랑', 'Bertrand'],
        ['모렐', 'Morel'], ['푸르니에', 'Fournier'], ['보네', 'Bonnet'], ['뒤퐁', 'Dupont'], ['랑베르', 'Lambert'],
        ['루소', 'Rousseau'], ['뱅상', 'Vincent'], ['뮐러', 'Muller'], ['포르', 'Faure'], ['앙드레', 'André'],
        ['블랑', 'Blanc'], ['베르제', 'Berger'], ['로지에', 'Rosier'], ['콜랭', 'Colin'], ['제르베', 'Gervais'],
        ["펠리시에", "Pélissier"], ["델마스", "Delmas"], ["리에나르", "Liénard"], ["포파나", "Fofana"], ["디아뉴", "Diagne"],
        ["코네", "Koné"], ["샤베르", "Chabert"], ["에스테브", "Estève"], ["로슈", "Roche"], ["디오프", "Diop"],
        ["비에라", "Vieira"], ["디디에", "Didier"], ["라니에르", "Lanier"], ["마르샹", "Marchand"], ["가르니에", "Garnier"],
        ["슈발리에", "Chevalier"], ["르그랑", "Legrand"], ["고티에", "Gauthier"], ["페랭", "Perrin"], ["로뱅", "Robin"],
        ["클레망", "Clément"], ["니콜라", "Nicolas"], ["루셀", "Roussel"], ["마티외", "Mathieu"], ["마송", "Masson"],
        ["마르샬", "Marchal"], ["뒤발", "Duval"], ["드니", "Denis"], ["뒤몽", "Dumont"], ["르메르", "Lemaire"],
        ["노엘", "Noël"], ["뒤푸르", "Dufour"], ["뫼니에", "Meunier"], ["블랑샤르", "Blanchard"], ["리비에르", "Rivière"],
        ["브뤼네", "Brunet"], ["바르비에", "Barbier"], ["제라르", "Gérard"], ["르노", "Renaud"], ["르클레르", "Leclerc"],
        ["레이", "Rey"], ["롤랑", "Rolland"], ["피카르", "Picard"], ["프레보", "Prévost"], ["샤르팡티에", "Charpentier"],
        ["메나르", "Ménard"], ["데샹", "Deschamps"], ["플뢰리", "Fleury"], ["카르팡티에", "Carpentier"], ["루아예", "Royer"],
        ["위에", "Huet"], ["바롱", "Baron"], ["오베르", "Aubert"], ["카롱", "Caron"], ["부르주아", "Bourgeois"],
        ["퐁스", "Pons"], ["기요", "Guillot"], ["브누아", "Benoît"], ["슈미트", "Schmitt"], ["마르티넬리", "Martinelli"],
        ["트라오레", "Traoré"], ["페레이라", "Pereira"],
      ],
      given: {
        female: [
          ['엘로디', 'Élodie'], ['카미유', 'Camille'], ['마농', 'Manon'], ['셀린', 'Céline'], ['아멜리', 'Amélie'],
          ['클로에', 'Chloé'], ['소피', 'Sophie'], ['리즈', 'Lise'], ['자드', 'Jade'], ['루이즈', 'Louise'],
          ['에마', 'Emma'], ['알리스', 'Alice'], ['앙브르', 'Ambre'], ['리나', 'Lina'], ['로즈', 'Rose'],
          ['미아', 'Mia'], ['레아', 'Léa'], ['안나', 'Anna'], ['밀라', 'Mila'], ['이네스', 'Inès'],
          ['줄리아', 'Julia'], ['레나', 'Léna'], ['조에', 'Zoé'], ['줄리엣', 'Juliette'], ['아가트', 'Agathe'],
          ['클라라', 'Clara'], ['가랑스', 'Garance'], ['마르고', 'Margot'], ['로만', 'Romane'], ['루시', 'Lucie'],
          ['샤를로트', 'Charlotte'], ['엘리즈', 'Élise'], ['마틸드', 'Mathilde'], ['오세안', 'Océane'], ['잔', 'Jeanne'],
          ["르네", "Renée"], ["아네트", "Annette"], ["에브", "Ève"], ["마를렌", "Marlène"], ["코랄린", "Coraline"],
          ["마리", "Marie"], ["마리안느", "Marianne"], ["마르그리트", "Marguerite"], ["이본", "Yvonne"], ["가브리엘", "Gabrielle"],
          ["셀리나", "Célina"], ["미셸", "Michèle"], ["레아나", "Léana"], ["레오니", "Léonie"], ["록산느", "Roxane"],
          ["롤라", "Lola"], ["모니크", "Monique"], ["발레리", "Valérie"], ["베로니크", "Véronique"], ["베르나데트", "Bernadette"],
          ["비비안", "Viviane"], ["오드", "Aude"], ["아녜스", "Agnès"], ["이자벨", "Isabelle"], ["마엘", "Maëlle"],
          ["콜레트", "Colette"], ["테레즈", "Thérèse"], ["솔렌", "Solène"], ["리제트", "Lisette"], ["브리지트", "Brigitte"],
          ["미레유", "Mireille"], ["이베트", "Yvette"], ["마리네트", "Marinette"],
        ],
        male: [
          ['뤼시앵', 'Lucien'], ['가스파르', 'Gaspard'], ['앙투안', 'Antoine'], ['쥘', 'Jules'], ['테오', 'Théo'],
          ['레미', 'Rémy'], ['루이', 'Louis'], ['바티스트', 'Baptiste'], ['가브리엘', 'Gabriel'], ['레오', 'Léo'],
          ['라파엘', 'Raphaël'], ['아르튀르', 'Arthur'], ['아담', 'Adam'], ['마엘', 'Maël'], ['루카', 'Luca'],
          ['노아', 'Noah'], ['리암', 'Liam'], ['폴', 'Paul'], ['알렉상드르', 'Alexandre'], ['아론', 'Aaron'],
          ['막심', 'Maxime'], ['클레망', 'Clément'], ['니콜라', 'Nicolas'], ['기욤', 'Guillaume'], ['아드리앙', 'Adrien'],
          ['줄리앵', 'Julien'], ['피에르', 'Pierre'], ['마티스', 'Mathis'], ['엘리엇', 'Eliott'], ['에르베', 'Hervé'],
          ['웨슬리', 'Wesley'], ['제레미', 'Jérémy'], ['아르센', 'Arsène'], ['노엘', 'Noël'], ['닐', 'Nil'],
          ['로랑', 'Laurent'], ['로베르', 'Robert'], ["르네", "René"], ["레지스", "Régis"], ["리오넬", "Lionel"],
          ["에드가르", "Edgar"], ["노르베르", "Norbert"], ["이시도르", "Isidore"], ["세드릭", "Cédric"], ["마르소", "Marceau"],
          ["멜빈", "Melvin"], ["브루노", "Bruno"], ["아르노", "Arnaud"], ["알렉스", "Alex"], ["에밀", "Émile"],
          ["에단", "Ethan"], ["에두아르", "Édouard"], ["엔조", "Enzo"], ["이자크", "Isaac"], ["티에리", "Thierry"],
          ["프레데릭", "Frédéric"], ["파스칼", "Pascal"], ["제롬", "Jérôme"], ["자크", "Jacques"], ["라울", "Raoul"],
          ["리샤르", "Richard"], ["마르셀", "Marcel"], ["마르크", "Marc"], ["마티아스", "Mathias"], ["모리스", "Maurice"],
          ["브누아", "Benoît"], ["빅토르", "Victor"],
        ],
        unisex: [
          ['카미유', 'Camille'], ['사샤', 'Sacha'], ["클로드", "Claude"], ["도미니크", "Dominique"],
        ],
      },
    },
    de: {
      ko: '독일', region: 'europe', order: 'west',
      surnames: [
        ['슈바르츠', 'Schwarz'], ['베버', 'Weber'], ['하르트만', 'Hartmann'], ['폰 아이헨', 'von Eichen'], ['뮐러', 'Müller'],
        ['크라우제', 'Krause'], ['로젠탈', 'Rosenthal'], ['베커', 'Becker'], ['슈미트', 'Schmidt'], ['슈나이더', 'Schneider'],
        ['피셔', 'Fischer'], ['마이어', 'Meyer'], ['바그너', 'Wagner'], ['슐츠', 'Schulz'], ['호프만', 'Hoffmann'],
        ['셰퍼', 'Schäfer'], ['코흐', 'Koch'], ['바우어', 'Bauer'], ['리히터', 'Richter'], ['클라인', 'Klein'],
        ['볼프', 'Wolf'], ['슈뢰더', 'Schröder'], ['노이만', 'Neumann'], ['브라운', 'Braun'], ['크뤼거', 'Krüger'],
        ['랑게', 'Lange'], ['켈러', 'Keller'], ['베르너', 'Werner'], ['레만', 'Lehmann'], ['하인리히', 'Heinrich'],
        ['쾨니히', 'König'], ["크나우어", "Knauer"],
      ],
      given: {
        female: [
          ['클라라', 'Clara'], ['리젤', 'Liesel'], ['한나', 'Hanna'], ['프리다', 'Frieda'], ['마를레네', 'Marlene'],
          ['엠마', 'Emma'], ['레아', 'Lea'], ['이레네', 'Irene'], ['미아', 'Mia'], ['에밀리아', 'Emilia'],
          ['소피아', 'Sophia'], ['리나', 'Lina'], ['안나', 'Anna'], ['밀라', 'Mila'], ['마리', 'Marie'],
          ['레나', 'Lena'], ['루이사', 'Luisa'], ['레오니', 'Leonie'], ['레니', 'Leni'], ['에밀리', 'Emilie'],
          ['아멜리', 'Amelie'], ['마틸다', 'Mathilda'], ['요한나', 'Johanna'], ['율리아', 'Julia'], ['사라', 'Sarah'],
          ['라우라', 'Laura'], ['넬레', 'Nele'], ['샬로트', 'Charlotte'], ['조피', 'Sophie'], ['빅토리아', 'Viktoria'],
          ['카타리나', 'Katharina'], ['니나', 'Nina'],
        ],
        male: [
          ['루카스', 'Lukas'], ['펠릭스', 'Felix'], ['막시밀리안', 'Maximilian'], ['요나스', 'Jonas'], ['레온', 'Leon'],
          ['에리히', 'Erich'], ['크리스토프', 'Christoph'], ['파울', 'Paul'], ['벤', 'Ben'], ['핀', 'Finn'],
          ['엘리아스', 'Elias'], ['루이스', 'Luis'], ['노아', 'Noah'], ['에밀', 'Emil'], ['루카', 'Luca'],
          ['율리안', 'Julian'], ['마테오', 'Matteo'], ['오스카', 'Oskar'], ['안톤', 'Anton'], ['필립', 'Philipp'],
          ['야코프', 'Jakob'], ['밀란', 'Milan'], ['모리츠', 'Moritz'], ['율리우스', 'Julius'], ['요하네스', 'Johannes'],
          ['알렉산더', 'Alexander'], ['다비드', 'David'], ['플로리안', 'Florian'], ['발렌틴', 'Valentin'], ['토비아스', 'Tobias'],
          ['크리스티안', 'Christian'], ['디트리히', 'Dietrich'], ['프리드리히', 'Friedrich'], ['알프레드', 'Alfred'], ['로베르트', 'Robert'],
          ['레오폴트', 'Leopold'], ['아르노', 'Arno'],
        ],
      },
    },
    it: {
      ko: '이탈리아', region: 'europe', order: 'west',
      surnames: [
        ['로시', 'Rossi'], ['루소', 'Russo'], ['페라리', 'Ferrari'], ['에스포지토', 'Esposito'], ['비앙키', 'Bianchi'],
        ['로마노', 'Romano'], ['콜롬보', 'Colombo'], ['리치', 'Ricci'], ['마리노', 'Marino'], ['그레코', 'Greco'],
        ['브루노', 'Bruno'], ['갈로', 'Gallo'], ['콘티', 'Conti'], ['데 루카', 'De Luca'], ['코스타', 'Costa'],
        ['조르다노', 'Giordano'], ['만치니', 'Mancini'], ['리초', 'Rizzo'], ['롬바르디', 'Lombardi'], ['모레티', 'Moretti'],
        ['바르비에리', 'Barbieri'], ['폰타나', 'Fontana'], ['산토로', 'Santoro'], ['마리아니', 'Mariani'], ['리날디', 'Rinaldi'],
        ['카루소', 'Caruso'], ['페라라', 'Ferrara'], ['갈리', 'Galli'], ['마르티니', 'Martini'], ['레오네', 'Leone'],
      ],
      given: {
        female: [
          ['로레타', 'Loretta'], ['소피아', 'Sofia'], ['줄리아', 'Giulia'], ['아우로라', 'Aurora'], ['알리체', 'Alice'],
          ['지네브라', 'Ginevra'], ['엠마', 'Emma'], ['조르자', 'Giorgia'], ['그레타', 'Greta'], ['베아트리체', 'Beatrice'],
          ['마르티나', 'Martina'], ['키아라', 'Chiara'], ['비토리아', 'Vittoria'], ['사라', 'Sara'], ['알레시아', 'Alessia'],
          ['프란체스카', 'Francesca'], ['노에미', 'Noemi'], ['니콜', 'Nicole'], ['비앙카', 'Bianca'], ['아리안나', 'Arianna'],
          ['마틸데', 'Matilde'], ['엘레나', 'Elena'], ['카밀라', 'Camilla'], ['루도비카', 'Ludovica'], ['마르게리타', 'Margherita'],
          ['세레나', 'Serena'], ['이사벨라', 'Isabella'], ['일라리아', 'Ilaria'], ['발렌티나', 'Valentina'], ['로베르타', 'Roberta'],
          ['라우라', 'Laura'], ["안젤라", "Angela"],
        ],
        male: [
          ['레오나르도', 'Leonardo'], ['프란체스코', 'Francesco'], ['알레산드로', 'Alessandro'], ['로렌초', 'Lorenzo'], ['마티아', 'Mattia'],
          ['안드레아', 'Andrea'], ['가브리엘레', 'Gabriele'], ['리카르도', 'Riccardo'], ['토마소', 'Tommaso'], ['에도아르도', 'Edoardo'],
          ['마테오', 'Matteo'], ['주세페', 'Giuseppe'], ['안토니오', 'Antonio'], ['조반니', 'Giovanni'], ['줄리오', 'Giulio'],
          ['필리포', 'Filippo'], ['마르코', 'Marco'], ['피에트로', 'Pietro'], ['사무엘레', 'Samuele'], ['알레시오', 'Alessio'],
          ['디에고', 'Diego'], ['다비데', 'Davide'], ['페데리코', 'Federico'], ['크리스티안', 'Christian'], ['발레리오', 'Valerio'],
          ['빈첸초', 'Vincenzo'], ['루이지', 'Luigi'], ['로베르토', 'Roberto'], ['스테파노', 'Stefano'], ['파올로', 'Paolo'],
          ['레나토', 'Renato'],
        ],
      },
    },
    es: {
      ko: '스페인', region: 'europe', order: 'west',
      surnames: [
        ['가르시아', 'García'], ['페르난데스', 'Fernández'], ['곤살레스', 'González'], ['로드리게스', 'Rodríguez'], ['로페스', 'López'],
        ['마르티네스', 'Martínez'], ['산체스', 'Sánchez'], ['페레스', 'Pérez'], ['고메스', 'Gómez'], ['마르틴', 'Martín'],
        ['루이스', 'Ruiz'], ['에르난데스', 'Hernández'], ['히메네스', 'Jiménez'], ['디아스', 'Díaz'], ['알바레스', 'Álvarez'],
        ['모레노', 'Moreno'], ['무뇨스', 'Muñoz'], ['알론소', 'Alonso'], ['구티에레스', 'Gutiérrez'], ['로메로', 'Romero'],
        ['나바로', 'Navarro'], ['토레스', 'Torres'], ['도밍게스', 'Domínguez'], ['라미레스', 'Ramírez'], ['블랑코', 'Blanco'],
        ['아길라르', 'Aguilar'], ['크루스', 'Cruz'], ['오르티스', 'Ortiz'], ['실바', 'Silva'], ['레예스', 'Reyes'],
        ['멘데스', 'Méndez'], ['마르코스', 'Marcos'],
        ["플로레스", "Flores"], ["리베라", "Rivera"], ["산티아고", "Santiago"], ["카스티요", "Castillo"], ["바스케스", "Vázquez"],
        ["카스트로", "Castro"], ["오르테가", "Ortega"], ["델가도", "Delgado"], ["수아레스", "Suárez"], ["라모스", "Ramos"],
        ["로하스", "Rojas"], ["모랄레스", "Morales"], ["에레라", "Herrera"], ["메디나", "Medina"], ["카브레라", "Cabrera"],
        ["캄포스", "Campos"], ["베가", "Vega"], ["몰리나", "Molina"], ["로사스", "Rosas"], ["산타나", "Santana"],
        ["에스트라다", "Estrada"], ["코르테스", "Cortés"], ["살라사르", "Salazar"], ["페냐", "Peña"], ["이바녜스", "Ibáñez"],
        ["파스토르", "Pastor"], ["갈란", "Galán"], ["로보", "Lobo"], ["사에스", "Sáez"], ["베니테스", "Benítez"],
        ["칸테로", "Cantero"], ["몬토야", "Montoya"], ["사발라", "Zabala"], ["아르멘다리스", "Armendáriz"], ["벨몬테", "Belmonte"],
        ["카사노바스", "Casanovas"], ["오소리오", "Osorio"], ["살바도르", "Salvador"], ["페레르", "Ferrer"], ["솔레르", "Soler"],
        ["리바스", "Rivas"], ["로카", "Roca"], ["비달", "Vidal"], ["세라", "Serra"], ["에체베리아", "Etxeberria"],
        ["우리베", "Uribe"], ["사라테", "Zárate"], ["아르사멘디", "Arzamendi"], ["세이하스", "Seijas"], ["오테로", "Otero"],
        ["하이메", "Jaime"],
      ],
      given: {
        female: [
          ['루시아', 'Lucía'], ['마르티나', 'Martina'], ['소피아', 'Sofía'], ['마리아', 'María'], ['발레리아', 'Valeria'],
          ['훌리아', 'Julia'], ['파울라', 'Paula'], ['다니엘라', 'Daniela'], ['카를라', 'Carla'], ['알바', 'Alba'],
          ['노아', 'Noa'], ['카르멘', 'Carmen'], ['클라우디아', 'Claudia'], ['발렌티나', 'Valentina'], ['알마', 'Alma'],
          ['아나', 'Ana'], ['라우라', 'Laura'], ['엘레나', 'Elena'], ['블랑카', 'Blanca'], ['아이타나', 'Aitana'],
          ['베가', 'Vega'], ['롤라', 'Lola'], ['빅토리아', 'Victoria'], ['카밀라', 'Camila'], ['이사벨', 'Isabel'],
          ['안토니아', 'Antonia'], ['실비아', 'Silvia'], ['베아트리스', 'Beatriz'], ['나탈리아', 'Natalia'], ['에스텔라', 'Estela'],
          ['로사나', 'Rosana'], ["후아나", "Juana"], ["아델라", "Adela"],
          ["사라", "Sara"], ["이레네", "Irene"], ["클라라", "Clara"], ["루크레시아", "Lucrecia"], ["노라", "Nora"],
          ["안드레아", "Andrea"], ["미아", "Mía"], ["아드리아나", "Adriana"], ["셀레나", "Selena"], ["하비에라", "Javiera"],
          ["마리아나", "Mariana"], ["파울리나", "Paulina"], ["레티시아", "Leticia"], ["루르데스", "Lourdes"], ["필라르", "Pilar"],
          ["메르세데스", "Mercedes"], ["로시오", "Rocío"], ["소라야", "Soraya"], ["히메나", "Jimena"], ["사비나", "Sabina"],
          ["엘사", "Elsa"], ["이네스", "Inés"], ["누리아", "Nuria"], ["파트리시아", "Patricia"], ["가브리엘라", "Gabriela"],
          ["크리스티나", "Cristina"], ["셀리아", "Celia"], ["알레한드라", "Alejandra"], ["에스페란사", "Esperanza"], ["솔레다드", "Soledad"],
          ["레메디오스", "Remedios"], ["이사도라", "Isadora"], ["아말리아", "Amalia"], ["카탈리나", "Catalina"], ["마그달레나", "Magdalena"],
          ["미란다", "Miranda"], ["프란시스카", "Francisca"], ["마이아", "Maia"], ["비앙카", "Bianca"], ["다나", "Dana"],
          ["헤네시스", "Génesis"], ["엘리사", "Elisa"], ["레아", "Lea"], ["애슐리", "Ashley"], ["아이노아", "Ainhoa"],
          ["키아라", "Kiara"], ["베르타", "Berta"], ["미리암", "Miriam"], ["알리시아", "Alicia"],
        ],
        male: [
          ['알레한드로', 'Alejandro'], ['마테오', 'Mateo'], ['우고', 'Hugo'], ['마르틴', 'Martín'], ['루카스', 'Lucas'],
          ['레오', 'Leo'], ['다니엘', 'Daniel'], ['파블로', 'Pablo'], ['마누엘', 'Manuel'], ['알바로', 'Álvaro'],
          ['아드리안', 'Adrián'], ['다비드', 'David'], ['마리오', 'Mario'], ['엔조', 'Enzo'], ['디에고', 'Diego'],
          ['마르코스', 'Marcos'], ['이산', 'Izan'], ['하비에르', 'Javier'], ['마르코', 'Marco'], ['티아고', 'Thiago'],
          ['카를로스', 'Carlos'], ['호르헤', 'Jorge'], ['안토니오', 'Antonio'], ['미겔', 'Miguel'], ['후안', 'Juan'],
          ['가브리엘', 'Gabriel'], ['펠리페', 'Felipe'], ['안드레스', 'Andrés'], ['이그나시오', 'Ignacio'], ['로드리고', 'Rodrigo'],
          ['레나토', 'Renato'],
          ["니콜라스", "Nicolás"], ["사무엘", "Samuel"], ["세르히오", "Sergio"], ["헥토르", "Héctor"], ["라울", "Raúl"],
          ["루벤", "Rubén"], ["오스카르", "Óscar"], ["이반", "Iván"], ["브루노", "Bruno"], ["엠마누엘", "Emmanuel"],
          ["크리스티안", "Cristian"], ["페드로", "Pedro"], ["프란시스코", "Francisco"], ["루이스", "Luis"], ["페르난도", "Fernando"],
          ["알베르토", "Alberto"], ["리카르도", "Ricardo"], ["에두아르도", "Eduardo"], ["에르네스토", "Ernesto"], ["살바도르", "Salvador"],
          ["호아킨", "Joaquín"], ["산티아고", "Santiago"], ["알론소", "Alonso"], ["에밀리오", "Emilio"], ["라파엘", "Rafael"],
          ["비센테", "Vicente"], ["마르셀로", "Marcelo"], ["아우구스토", "Augusto"], ["레안드로", "Leandro"], ["세바스티안", "Sebastián"],
          ["로렌소", "Lorenzo"], ["베니토", "Benito"], ["발렌틴", "Valentín"], ["옥타비오", "Octavio"], ["비엘", "Biel"],
          ["엘리아스", "Elías"], ["에스테반", "Esteban"], ["딜란", "Dylan"], ["가스파르", "Gaspar"], ["아벨", "Abel"],
          ["로헤르", "Roger"], ["이제키엘", "Ezequiel"], ["에드윈", "Edwin"], ["이안", "Ian"], ["아론", "Aarón"],
          ["파비안", "Fabián"], ["헤수스", "Jesús"],
        ],
        unisex: [
          ["아리엘", "Ariel"], ["알렉시스", "Alexis"], ["요반니", "Yovanni"],
        ],
      },
    },
    // 무국적: 이름은 모든 나라 목록에서 랜덤
    nl: {
      ko: '네덜란드', region: 'europe', order: 'west',
      surnames: [
        ['데 용', 'de Jong'], ['얀선', 'Jansen'], ['데 프리스', 'de Vries'], ['판 덴 베르흐', 'van den Berg'], ['판 다이크', 'van Dijk'],
        ['바커르', 'Bakker'], ['얀센', 'Janssen'], ['피서르', 'Visser'], ['스밋', 'Smit'], ['메이어르', 'Meijer'],
        ['데 부르', 'de Boer'], ['뮐더르', 'Mulder'], ['데 흐로트', 'de Groot'], ['보스', 'Bos'], ['포스', 'Vos'],
        ['페이터르스', 'Peters'], ['헨드릭스', 'Hendriks'], ['판 레이우언', 'van Leeuwen'], ['데커르', 'Dekker'], ['브라우어르', 'Brouwer'],
        ['데 빗', 'de Wit'], ['다이크스트라', 'Dijkstra'], ['스밋스', 'Smits'], ['데 흐라프', 'de Graaf'], ['판 데르 메이르', 'van der Meer'],
        ['판 데르 린던', 'van der Linden'], ['콕', 'Kok'], ['야콥스', 'Jacobs'], ['데 한', 'de Haan'], ['페르뮐런', 'Vermeulen'],
        ['판 덴 회벌', 'van den Heuvel'], ['판 데르 페인', 'van der Veen'], ['판 덴 브룩', 'van den Broek'], ['데 브라윈', 'de Bruijn'], ['빌럼선', 'Willemsen'],
        ['카위퍼르스', 'Kuipers'], ['판 베이크', 'van Beek'], ['판 담', 'van Dam'], ['훅스트라', 'Hoekstra'], ['마스', 'Maas'],
      ],
      given: {
        female: [
          ['안나', 'Anna'], ['엠마', 'Emma'], ['율리아', 'Julia'], ['소피', 'Sophie'], ['밀라', 'Mila'],
          ['테스', 'Tess'], ['산네', 'Sanne'], ['로테', 'Lotte'], ['펨케', 'Femke'], ['아노크', 'Anouk'],
          ['마리케', 'Marieke'], ['사스키아', 'Saskia'], ['빌레마인', 'Willemijn'], ['플뢰르', 'Fleur'], ['에바', 'Eva'],
          ['리케', 'Lieke'], ['마우트', 'Maud'], ['로스', 'Roos'], ['닌케', 'Nienke'], ['브레흐예', 'Bregje'],
          ['한나', 'Hanna'], ['리사', 'Lisa'], ['에스메', 'Esmee'], ['야스마인', 'Jasmijn'], ['일세', 'Ilse'],
          ['메럴', 'Merel'], ['페이를러', 'Veerle'], ['카티아', 'Katja'], ['엘스', 'Els'], ['다프네', 'Daphne'],
          ['암베르', 'Amber'], ['야라', 'Yara'], ['루스', 'Loes'], ['마리트', 'Marit'], ['에벨린', 'Eveline'],
        ],
        male: [
          ['단', 'Daan'], ['셈', 'Sem'], ['뤼카스', 'Lucas'], ['레비', 'Levi'], ['핀', 'Finn'],
          ['브람', 'Bram'], ['예세', 'Jesse'], ['밀란', 'Milan'], ['뤽', 'Luuk'], ['스벤', 'Sven'],
          ['타이스', 'Thijs'], ['요스트', 'Joost'], ['피터르', 'Pieter'], ['예룬', 'Jeroen'], ['바스', 'Bas'],
          ['쿤', 'Koen'], ['마르턴', 'Maarten'], ['빌렘', 'Willem'], ['헨드릭', 'Hendrik'], ['얀', 'Jan'],
          ['케이스', 'Kees'], ['뤼트거르', 'Rutger'], ['스타인', 'Stijn'], ['튼', 'Teun'], ['하이스', 'Gijs'],
          ['룰', 'Roel'], ['디르크', 'Dirk'], ['닐스', 'Niels'], ['바우터르', 'Wouter'], ['플로리스', 'Floris'],
          ['산더르', 'Sander'], ['뤼번', 'Ruben'], ['카스퍼르', 'Casper'], ['메이스', 'Mees'], ['히스베르트', 'Gijsbert'],
        ],
        unisex: [
          ['로빈', 'Robin'], ['노아', 'Noa'],
        ],
      },
    },
    be: {
      ko: '벨기에', region: 'europe', shares: ['nl', 'fr'],
      // 네덜란드어권(플란데런) + 프랑스어권(왈롱) 목록 + 벨기에에 특히 많은 성씨
      extra: {
        rate: 0.45,
        surnames: [
          ['페이터르스', 'Peeters'], ['얀선스', 'Janssens'], ['마스', 'Maes'], ['메르턴스', 'Mertens'], ['빌럼스', 'Willems'],
          ['클라스', 'Claes'], ['호선스', 'Goossens'], ['바우터르스', 'Wouters'], ['데 스메트', 'De Smet'], ['데 클레르크', 'De Clercq'],
          ['판데르메르스', 'Vandermeersch'], ['판 담메', 'Van Damme'], ['판 홉', 'Van Hoof'], ['드 코닝크', 'De Coninck'], ['베르헤이던', 'Verheyden'],
          ['람베르', 'Lambert'], ['뒤퐁', 'Dupont'], ['르루아', 'Leroy'], ['르페브르', 'Lefebvre'], ['드 스멧', 'Desmet'],
          ['질', 'Gilles'], ['앙리옹', 'Henrion'], ['콜랭', 'Collin'], ['보드손', 'Baudson'],
        ],
        given: {},
      },
    },
    at: {
      ko: '오스트리아', region: 'europe', shares: ['de'],
      // 독일 목록 + 오스트리아에 특히 많은 성씨·이름
      extra: {
        rate: 0.45,
        surnames: [
          ['그루버', 'Gruber'], ['후버', 'Huber'], ['피클러', 'Pichler'], ['슈타이너', 'Steiner'], ['모저', 'Moser'],
          ['호퍼', 'Hofer'], ['라이트너', 'Leitner'], ['베르거', 'Berger'], ['푹스', 'Fuchs'], ['에더', 'Eder'],
          ['슈미트', 'Schmid'], ['빙클러', 'Winkler'], ['마이어', 'Maier'], ['브루너', 'Brunner'], ['랑', 'Lang'],
          ['바움가르트너', 'Baumgartner'], ['에거', 'Egger'], ['라이터', 'Reiter'], ['비머', 'Wimmer'], ['아우어', 'Auer'],
          ['아이그너', 'Aigner'], ['하스', 'Haas'], ['에브너', 'Ebner'], ['콜러', 'Koller'], ['슈타들러', 'Stadler'],
        ],
        given: {
          female: [
            ['엘리자베트', 'Elisabeth'], ['테레사', 'Theresa'], ['마그달레나', 'Magdalena'], ['발렌티나', 'Valentina'], ['로미', 'Romy'],
            ['한나', 'Hannah'], ['레오니', 'Leonie'], ['이자벨', 'Isabel'], ['알마', 'Alma'], ['클라라', 'Klara'],
          ],
          male: [
            ['제바스티안', 'Sebastian'], ['마티아스', 'Matthias'], ['안드레아스', 'Andreas'], ['슈테판', 'Stefan'], ['마르쿠스', 'Markus'],
            ['요제프', 'Josef'], ['프란츠', 'Franz'], ['하네스', 'Hannes'], ['게르노트', 'Gernot'], ['페르디난트', 'Ferdinand'],
          ],
        },
      },
    },
    se: {
      ko: '스웨덴', region: 'europe', order: 'west',
      surnames: [
        ['안데르손', 'Andersson'], ['요한손', 'Johansson'], ['칼손', 'Karlsson'], ['닐손', 'Nilsson'], ['에릭손', 'Eriksson'],
        ['라르손', 'Larsson'], ['올손', 'Olsson'], ['페르손', 'Persson'], ['스벤손', 'Svensson'], ['구스타프손', 'Gustafsson'],
        ['페테르손', 'Pettersson'], ['욘손', 'Jonsson'], ['얀손', 'Jansson'], ['한손', 'Hansson'], ['벵트손', 'Bengtsson'],
        ['옌손', 'Jönsson'], ['린드베리', 'Lindberg'], ['야콥손', 'Jakobsson'], ['망누손', 'Magnusson'], ['린드스트룀', 'Lindström'],
        ['린드크비스트', 'Lindqvist'], ['린드그렌', 'Lindgren'], ['베리', 'Berg'], ['악셀손', 'Axelsson'], ['베리스트룀', 'Bergström'],
        ['룬드베리', 'Lundberg'], ['린드', 'Lind'], ['룬드그렌', 'Lundgren'], ['베리룬드', 'Berglund'], ['프레드릭손', 'Fredriksson'],
        ['산드베리', 'Sandberg'], ['마트손', 'Mattsson'], ['엑스트룀', 'Ekström'], ['홀름', 'Holm'], ['포르스베리', 'Forsberg'],
        ['뉘스트룀', 'Nyström'], ['쇠데르베리', 'Söderberg'], ['달베리', 'Dahlberg'],
      ],
      given: {
        female: [
          ['안나', 'Anna'], ['엠마', 'Emma'], ['알리세', 'Alice'], ['마야', 'Maja'], ['엘사', 'Elsa'],
          ['아스트리드', 'Astrid'], ['잉리드', 'Ingrid'], ['린네아', 'Linnea'], ['클라라', 'Klara'], ['에바', 'Ebba'],
          ['프레야', 'Freja'], ['아그네스', 'Agnes'], ['사가', 'Saga'], ['시그네', 'Signe'], ['토베', 'Tove'],
          ['빌마', 'Wilma'], ['알바', 'Alva'], ['엘린', 'Elin'], ['사라', 'Sara'], ['로비사', 'Lovisa'],
          ['마틸다', 'Matilda'], ['시리', 'Siri'], ['그레타', 'Greta'], ['한나', 'Hanna'], ['카린', 'Karin'],
          ['셰르스틴', 'Kerstin'], ['말린', 'Malin'], ['안니카', 'Annika'], ['비르기타', 'Birgitta'], ['윌바', 'Ylva'],
          ['스티나', 'Stina'], ['메르타', 'Märta'], ['노바', 'Nova'], ['잉에보리', 'Ingeborg'],
        ],
        male: [
          ['루카스', 'Lucas'], ['리암', 'Liam'], ['빌리암', 'William'], ['엘리아스', 'Elias'], ['오스카르', 'Oscar'],
          ['휘고', 'Hugo'], ['악셀', 'Axel'], ['에리크', 'Erik'], ['요한', 'Johan'], ['칼', 'Karl'],
          ['라르스', 'Lars'], ['안데르스', 'Anders'], ['닐스', 'Nils'], ['구스타브', 'Gustav'], ['스벤', 'Sven'],
          ['비에른', 'Björn'], ['마그누스', 'Magnus'], ['헨리크', 'Henrik'], ['마티아스', 'Mattias'], ['프레드리크', 'Fredrik'],
          ['올로프', 'Olof'], ['에밀', 'Emil'], ['빅토르', 'Viktor'], ['알빈', 'Albin'], ['비다르', 'Vidar'],
          ['레이프', 'Leif'], ['루네', 'Rune'], ['스텔란', 'Stellan'], ['투레', 'Ture'], ['알바르', 'Alvar'],
          ['요나스', 'Jonas'], ['페르', 'Per'], ['토비아스', 'Tobias'], ['몬스', 'Måns'],
        ],
        unisex: [
          ['킴', 'Kim'], ['로빈', 'Robin'],
        ],
      },
    },
    dk: {
      ko: '덴마크', region: 'europe', order: 'west',
      surnames: [
        ['옌센', 'Jensen'], ['닐센', 'Nielsen'], ['한센', 'Hansen'], ['페데르센', 'Pedersen'], ['안데르센', 'Andersen'],
        ['크리스텐센', 'Christensen'], ['라르센', 'Larsen'], ['쇠렌센', 'Sørensen'], ['라스무센', 'Rasmussen'], ['예르겐센', 'Jørgensen'],
        ['페테르센', 'Petersen'], ['마센', 'Madsen'], ['크리스텐센', 'Kristensen'], ['올센', 'Olsen'], ['톰센', 'Thomsen'],
        ['크리스티안센', 'Christiansen'], ['포울센', 'Poulsen'], ['요한센', 'Johansen'], ['묄러', 'Møller'], ['모르텐센', 'Mortensen'],
        ['크누센', 'Knudsen'], ['야콥센', 'Jakobsen'], ['스미트', 'Schmidt'], ['홀름', 'Holm'], ['룬', 'Lund'],
        ['키에르', 'Kjær'], ['바크', 'Bak'], ['달', 'Dahl'], ['브룬', 'Bruun'], ['빈터', 'Vinter'],
        ['프리스', 'Friis'], ['토프트', 'Toft'], ['담고르', 'Damgaard'], ['외스터고르', 'Østergaard'], ['크로', 'Krogh'],
      ],
      given: {
        female: [
          ['엠마', 'Emma'], ['이다', 'Ida'], ['프레야', 'Freja'], ['소피에', 'Sofie'], ['클라라', 'Clara'],
          ['칼라', 'Karla'], ['아그네스', 'Agnes'], ['알마', 'Alma'], ['요세피네', 'Josefine'], ['라우라', 'Laura'],
          ['안나', 'Anna'], ['메테', 'Mette'], ['시그네', 'Signe'], ['아스트리드', 'Astrid'], ['키르스텐', 'Kirsten'],
          ['잉거', 'Inger'], ['보딜', 'Bodil'], ['마렌', 'Maren'], ['틸데', 'Tilde'], ['레르케', 'Lærke'],
          ['난나', 'Nanna'], ['리케', 'Rikke'], ['트리네', 'Trine'], ['페르닐레', 'Pernille'], ['카밀라', 'Camilla'],
          ['비르기테', 'Birgitte'], ['헬레', 'Helle'], ['로네', 'Lone'], ['마리', 'Marie'], ['리바', 'Liva'],
          ['엘런', 'Ellen'], ['비베케', 'Vibeke'],
        ],
        male: [
          ['빌리암', 'William'], ['오스카', 'Oscar'], ['노아', 'Noah'], ['루카스', 'Lukas'], ['말테', 'Malthe'],
          ['알프레드', 'Alfred'], ['비고', 'Viggo'], ['마그누스', 'Magnus'], ['안데르스', 'Anders'], ['마스', 'Mads'],
          ['옌스', 'Jens'], ['쇠렌', 'Søren'], ['라르스', 'Lars'], ['닐스', 'Niels'], ['크리스티안', 'Christian'],
          ['프레데리크', 'Frederik'], ['카스퍼', 'Kasper'], ['미켈', 'Mikkel'], ['라스무스', 'Rasmus'], ['예스퍼', 'Jesper'],
          ['헨리크', 'Henrik'], ['비아르네', 'Bjarne'], ['크누드', 'Knud'], ['트롤스', 'Troels'], ['발데마르', 'Valdemar'],
          ['에밀', 'Emil'], ['아스거', 'Asger'], ['에스벤', 'Esben'], ['토르벤', 'Torben'], ['에리크', 'Erik'],
          ['올레', 'Ole'], ['포울', 'Poul'],
        ],
      },
    },
    fi: {
      ko: '핀란드', region: 'europe', order: 'west',
      surnames: [
        ['코르호넨', 'Korhonen'], ['비르타넨', 'Virtanen'], ['매키넨', 'Mäkinen'], ['니에미넨', 'Nieminen'], ['매켈래', 'Mäkelä'],
        ['하말라이넨', 'Hämäläinen'], ['라이네', 'Laine'], ['헤이키넨', 'Heikkinen'], ['코스키넨', 'Koskinen'], ['얘르비넨', 'Järvinen'],
        ['레흐토넨', 'Lehtonen'], ['레흐티넨', 'Lehtinen'], ['사리넨', 'Saarinen'], ['살미넨', 'Salminen'], ['헤이노넨', 'Heinonen'],
        ['니에미', 'Niemi'], ['헤이킬래', 'Heikkilä'], ['킨누넨', 'Kinnunen'], ['살로넨', 'Salonen'], ['투루넨', 'Turunen'],
        ['살로', 'Salo'], ['라이티넨', 'Laitinen'], ['투오미넨', 'Tuominen'], ['란타넨', 'Rantanen'], ['카르얄라이넨', 'Karjalainen'],
        ['요키넨', 'Jokinen'], ['마틸라', 'Mattila'], ['사볼라이넨', 'Savolainen'], ['라흐티넨', 'Lahtinen'], ['아호넨', 'Ahonen'],
        ['오얄라', 'Ojala'], ['레패넨', 'Leppänen'], ['칼리오', 'Kallio'], ['배이새넨', 'Väisänen'], ['힐투넨', 'Hiltunen'],
        ['알토', 'Aalto'],
      ],
      given: {
        female: [
          ['아이노', 'Aino'], ['엠마', 'Emma'], ['소피아', 'Sofia'], ['벤라', 'Venla'], ['아다', 'Aada'],
          ['헬미', 'Helmi'], ['엘라', 'Ella'], ['에비', 'Eevi'], ['릴리아', 'Lilja'], ['시리', 'Siiri'],
          ['마리아', 'Maria'], ['안니', 'Anni'], ['카이사', 'Kaisa'], ['리사', 'Liisa'], ['마리아타', 'Marjatta'],
          ['산니', 'Sanni'], ['투울리', 'Tuuli'], ['일로나', 'Ilona'], ['키르시', 'Kirsi'], ['피르요', 'Pirjo'],
          ['리카', 'Riikka'], ['엘리나', 'Elina'], ['한나', 'Hanna'], ['카타리나', 'Katariina'], ['라우라', 'Laura'],
          ['노라', 'Noora'], ['사나', 'Saana'], ['수비', 'Suvi'], ['테르히', 'Terhi'], ['바푸', 'Vappu'],
          ['미르카', 'Mirka'], ['오네르바', 'Onerva'],
        ],
        male: [
          ['온니', 'Onni'], ['엘리아스', 'Elias'], ['에이노', 'Eino'], ['배이뇌', 'Väinö'], ['토이보', 'Toivo'],
          ['레오', 'Leo'], ['알렉시', 'Aleksi'], ['미카엘', 'Mikael'], ['유하니', 'Juhani'], ['마티', 'Matti'],
          ['유카', 'Jukka'], ['페카', 'Pekka'], ['안티', 'Antti'], ['티모', 'Timo'], ['카리', 'Kari'],
          ['미코', 'Mikko'], ['빌레', 'Ville'], ['얀네', 'Janne'], ['사미', 'Sami'], ['투오마스', 'Tuomas'],
          ['베이코', 'Veikko'], ['올라비', 'Olavi'], ['타피오', 'Tapio'], ['에로', 'Eero'], ['일마리', 'Ilmari'],
          ['얄마리', 'Jalmari'], ['라우리', 'Lauri'], ['닐로', 'Niilo'], ['옷소', 'Otso'], ['라우노', 'Rauno'],
          ['세포', 'Seppo'], ['우르호', 'Urho'], ['칼레비', 'Kalevi'],
        ],
      },
    },
    gr: {
      ko: '그리스', region: 'europe', order: 'west',
      // 그리스 성씨는 성별에 따라 형태가 바뀐다 (-os 남성 / -ou 여성).
      // { m, f } 로 적은 것은 성별에 따라 갈리고, 배열로 적은 것은 남녀 같은 형태(속격 -ou)다.
      surnames: [
        { m: ['파파도풀로스', 'Papadopoulos'], f: ['파파도풀루', 'Papadopoulou'] },
        { m: ['파파다키스', 'Papadakis'], f: ['파파다키', 'Papadaki'] },
        { m: ['블라호스', 'Vlachos'], f: ['블라후', 'Vlachou'] },
        { m: ['마크리스', 'Makris'], f: ['마크리', 'Makri'] },
        { m: ['콘스탄티니디스', 'Konstantinidis'], f: ['콘스탄티니두', 'Konstantinidou'] },
        { m: ['카라이안니스', 'Karagiannis'], f: ['카라이안니', 'Karagianni'] },
        { m: ['파파스', 'Pappas'], f: ['파파', 'Pappa'] },
        { m: ['파나요토풀로스', 'Panagiotopoulos'], f: ['파나요토풀루', 'Panagiotopoulou'] },
        { m: ['미하일리디스', 'Michailidis'], f: ['미하일리두', 'Michailidou'] },
        { m: ['니콜라이디스', 'Nikolaidis'], f: ['니콜라이두', 'Nikolaidou'] },
        { m: ['스파노스', 'Spanos'], f: ['스파누', 'Spanou'] },
        { m: ['칼로예로풀로스', 'Kalogeropoulos'], f: ['칼로예로풀루', 'Kalogeropoulou'] },
        { m: ['폴리티스', 'Politis'], f: ['폴리티', 'Politi'] },
        { m: ['조그라포스', 'Zografos'], f: ['조그라푸', 'Zografou'] },
        { m: ['추칼라스', 'Tsoukalas'], f: ['추칼라', 'Tsoukala'] },
        { m: ['디아만티스', 'Diamantis'], f: ['디아만티', 'Diamanti'] },
        { m: ['루소스', 'Roussos'], f: ['루수', 'Roussou'] },
        { m: ['안겔로풀로스', 'Angelopoulos'], f: ['안겔로풀루', 'Angelopoulou'] },
        { m: ['하치스', 'Chatzis'], f: ['하치', 'Chatzi'] },
        { m: ['코스토풀로스', 'Kostopoulos'], f: ['코스토풀루', 'Kostopoulou'] },
        { m: ['레벤티스', 'Leventis'], f: ['레벤티', 'Leventi'] },
        { m: ['마브로스', 'Mavros'], f: ['마브루', 'Mavrou'] },
        { m: ['스테파니디스', 'Stefanidis'], f: ['스테파니두', 'Stefanidou'] },
        { m: ['안드레아디스', 'Andreadis'], f: ['안드레아두', 'Andreadou'] },
        { m: ['갈라니스', 'Galanis'], f: ['갈라니', 'Galani'] },
        { m: ['쿠르티스', 'Kourtis'], f: ['쿠르티', 'Kourti'] },
        { m: ['게르마노스', 'Germanos'], f: ['게르마누', 'Germanou'] },
        ['게오르기우', 'Georgiou'], ['니콜라우', 'Nikolaou'], ['요안누', 'Ioannou'], ['이코노무', 'Oikonomou'],
        ['디미트리우', 'Dimitriou'], ['안토니우', 'Antoniou'], ['파파니콜라우', 'Papanikolaou'], ['바실레이우', 'Vasileiou'],
        ['흐리스토둘루', 'Christodoulou'], ['아타나시우', 'Athanasiou'], ['스타브루', 'Stavrou'], ['페트루', 'Petrou'],
        ['알렉시우', 'Alexiou'], ['테오도루', 'Theodorou'], ['키리아쿠', 'Kyriakou'], ['포티우', 'Fotiou'],
        ['사켈라리우', 'Sakellariou'], ['트리안타필루', 'Triantafyllou'], ['람브루', 'Lambrou'], ['아나그노스투', 'Anagnostou'],
        ['파파조글루', 'Papazoglou'], ['아포스톨루', 'Apostolou'],
      ],
      given: {
        female: [
          ['마리아', 'Maria'], ['엘레니', 'Eleni'], ['카테리나', 'Katerina'], ['소피아', 'Sofia'], ['디미트라', 'Dimitra'],
          ['게오르기아', 'Georgia'], ['안나', 'Anna'], ['바실리키', 'Vasiliki'], ['이오안나', 'Ioanna'], ['콘스탄티나', 'Konstantina'],
          ['흐리스티나', 'Christina'], ['데스피나', 'Despina'], ['안겔리키', 'Angeliki'], ['파라스케비', 'Paraskevi'], ['스타브룰라', 'Stavroula'],
          ['이리니', 'Eirini'], ['칼리오피', 'Kalliopi'], ['아티나', 'Athina'], ['네펠리', 'Nefeli'], ['멜리나', 'Melina'],
          ['조이', 'Zoe'], ['탈리아', 'Thalia'], ['다나이', 'Danae'], ['하라', 'Chara'], ['에반겔리아', 'Evangelia'],
          ['마리나', 'Marina'], ['포티니', 'Fotini'], ['파나요타', 'Panagiota'], ['올가', 'Olga'], ['니키', 'Niki'],
          ['알렉산드라', 'Alexandra'], ['이리스', 'Iris'], ['리디아', 'Lydia'], ['페넬로피', 'Penelope'],
        ],
        male: [
          ['요르고스', 'Giorgos'], ['디미트리스', 'Dimitris'], ['콘스탄티노스', 'Konstantinos'], ['니코스', 'Nikos'], ['이오아니스', 'Ioannis'],
          ['파나요티스', 'Panagiotis'], ['바실리스', 'Vasilis'], ['흐리스토스', 'Christos'], ['알렉산드로스', 'Alexandros'], ['아타나시오스', 'Athanasios'],
          ['미할리스', 'Michalis'], ['페트로스', 'Petros'], ['스타브로스', 'Stavros'], ['타나시스', 'Thanasis'], ['안드레아스', 'Andreas'],
          ['안토니스', 'Antonis'], ['스텔리오스', 'Stelios'], ['마놀리스', 'Manolis'], ['스피로스', 'Spyros'], ['테오도로스', 'Theodoros'],
          ['일리아스', 'Ilias'], ['레프테리스', 'Lefteris'], ['코스타스', 'Kostas'], ['야니스', 'Yiannis'], ['포티스', 'Fotis'],
          ['그리고리스', 'Grigoris'], ['아리스', 'Aris'], ['오레스티스', 'Orestis'], ['레오니다스', 'Leonidas'], ['파블로스', 'Pavlos'],
          ['아힐레아스', 'Achilleas'], ['오디세아스', 'Odysseas'], ['하랄람보스', 'Charalambos'], ['타소스', 'Tasos'],
        ],
      },
    },
    none: { ko: '무국적', region: 'etc', anyName: true },
    ru: {
      ko: '러시아', region: 'europe', order: 'west',
      // 부칭(아버지 이름에서 만든 중간 이름) 중 규칙을 따르지 않는 것: [남성형, 여성형]
      patronymicExceptions: {
        Pavel: [['파블로비치', 'Pavlovich'], ['파블로브나', 'Pavlovna']],
        Lev: [['리보비치', 'Lvovich'], ['리보브나', 'Lvovna']],
        Pyotr: [['페트로비치', 'Petrovich'], ['페트로브나', 'Petrovna']],
        Yakov: [['야코블레비치', 'Yakovlevich'], ['야코블레브나', 'Yakovlevna']],
        Igor: [['이고레비치', 'Igorevich'], ['이고레브나', 'Igorevna']],
        Ilya: [['일리치', 'Ilyich'], ['일리니치나', 'Ilyinichna']],
        Nikita: [['니키티치', 'Nikitich'], ['니키티치나', 'Nikitichna']],
        Luka: [['루키치', 'Lukich'], ['루키니치나', 'Lukinichna']],
        Alexander: [['알렉산드로비치', 'Alexandrovich'], ['알렉산드로브나', 'Alexandrovna']],
        Felix: [['펠릭소비치', 'Feliksovich'], ['펠릭소브나', 'Feliksovna']],
        Philipp: [['필리포비치', 'Filippovich'], ['필리포브나', 'Filippovna']],
      },
      surnames: [
        { m: ['볼코프', 'Volkov'], f: ['볼코바', 'Volkova'] }, { m: ['이바노프', 'Ivanov'], f: ['이바노바', 'Ivanova'] }, { m: ['소콜로프', 'Sokolov'], f: ['소콜로바', 'Sokolova'] }, { m: ['모로조프', 'Morozov'], f: ['모로조바', 'Morozova'] }, { m: ['오를로프', 'Orlov'], f: ['오를로바', 'Orlova'] },
        { m: ['페트로프', 'Petrov'], f: ['페트로바', 'Petrova'] }, { m: ['스미르노프', 'Smirnov'], f: ['스미르노바', 'Smirnova'] }, { m: ['쿠즈네초프', 'Kuznetsov'], f: ['쿠즈네초바', 'Kuznetsova'] }, { m: ['로모프', 'Lomov'], f: ['로모바', 'Lomova'] }, { m: ['레베데프', 'Lebedev'], f: ['레베데바', 'Lebedeva'] },
        { m: ['코즐로프', 'Kozlov'], f: ['코즐로바', 'Kozlova'] }, { m: ['노비코프', 'Novikov'], f: ['노비코바', 'Novikova'] }, { m: ['솔로비요프', 'Solovyov'], f: ['솔로비요바', 'Solovyova'] }, { m: ['바실리예프', 'Vasiliev'], f: ['바실리예바', 'Vasilieva'] }, { m: ['자이체프', 'Zaitsev'], f: ['자이체바', 'Zaitseva'] },
        { m: ['세묘노프', 'Semyonov'], f: ['세묘노바', 'Semyonova'] }, { m: ['골루베프', 'Golubev'], f: ['골루베바', 'Golubeva'] }, { m: ['비노그라도프', 'Vinogradov'], f: ['비노그라도바', 'Vinogradova'] }, { m: ['보그다노프', 'Bogdanov'], f: ['보그다노바', 'Bogdanova'] }, { m: ['보로비요프', 'Vorobyov'], f: ['보로비요바', 'Vorobyova'] },
        { m: ['페도로프', 'Fyodorov'], f: ['페도로바', 'Fyodorova'] }, { m: ['미하일로프', 'Mikhailov'], f: ['미하일로바', 'Mikhailova'] }, { m: ['벨로프', 'Belov'], f: ['벨로바', 'Belova'] }, { m: ['타라소프', 'Tarasov'], f: ['타라소바', 'Tarasova'] }, { m: ['코마로프', 'Komarov'], f: ['코마로바', 'Komarova'] },
        { m: ['소로킨', 'Sorokin'], f: ['소로키나', 'Sorokina'] }, { m: ['니키틴', 'Nikitin'], f: ['니키티나', 'Nikitina'] }, { m: ['볼로딘', 'Volodin'], f: ['볼로디나', 'Volodina'] }, { m: ['일린', 'Ilyin'], f: ['일리나', 'Ilyina'] }, { m: ['사빈', 'Savin'], f: ['사비나', 'Savina'] },
        { m: ['쿠진', 'Kuzin'], f: ['쿠지나', 'Kuzina'] }, { m: ['루딘', 'Rudin'], f: ['루디나', 'Rudina'] }, { m: ['루빈', 'Rubin'], f: ['루비나', 'Rubina'] }, { m: ['벨린스키', 'Belinsky'], f: ['벨린스카야', 'Belinskaya'] }, { m: ['카멘스키', 'Kamensky'], f: ['카멘스카야', 'Kamenskaya'] },
        { m: ['코발스키', 'Kovalsky'], f: ['코발스카야', 'Kovalskaya'] }, ['솁첸코', 'Shevchenko'], ['크리벤코', 'Krivenko'], ['이그나텐코', 'Ignatenko'], ['타라센코', 'Tarasenko'],
        ['다첸코', 'Datsenko'], ['코발추크', 'Kovalchuk'], ['폴리슈크', 'Polishchuk'], ['본다르추크', 'Bondarchuk'], ['마르틴', 'Martin'],
        ['비도비치', 'Vidovich'], { m: ['샤토프', 'Shatov'], f: ['샤토바', 'Shatova'] }, { m: ['키릴로프', 'Kirillov'], f: ['키릴로바', 'Kirillova'] }, { m: ['야코블레프', 'Yakovlev'], f: ['야코블레바', 'Yakovleva'] }, { m: ['그리고리예프', 'Grigoriev'], f: ['그리고리예바', 'Grigorieva'] },
        { m: ['마카로프', 'Makarov'], f: ['마카로바', 'Makarova'] }, { m: ['자하로프', 'Zakharov'], f: ['자하로바', 'Zakharova'] }, { m: ['체르노프', 'Chernov'], f: ['체르노바', 'Chernova'] }, { m: ['벨랴예프', 'Belyaev'], f: ['벨랴예바', 'Belyaeva'] }, { m: ['티호노프', 'Tikhonov'], f: ['티호노바', 'Tikhonova'] },
        { m: ['고르데예프', 'Gordeev'], f: ['고르데예바', 'Gordeeva'] }, { m: ['데니소프', 'Denisov'], f: ['데니소바', 'Denisova'] }, { m: ['라자레프', 'Lazarev'], f: ['라자레바', 'Lazareva'] }, { m: ['멜니코프', 'Melnikov'], f: ['멜니코바', 'Melnikova'] }, { m: ['셰르바코프', 'Shcherbakov'], f: ['셰르바코바', 'Shcherbakova'] },
        { m: ['쿠드랴프체프', 'Kudryavtsev'], f: ['쿠드랴프체바', 'Kudryavtseva'] }, { m: ['우샤코프', 'Ushakov'], f: ['우샤코바', 'Ushakova'] }, { m: ['우스펜스키', 'Uspensky'], f: ['우스펜스카야', 'Uspenskaya'] }, { m: ['포크롭스키', 'Pokrovsky'], f: ['포크롭스카야', 'Pokrovskaya'] }, { m: ['소스놉스키', 'Sosnovsky'], f: ['소스놉스카야', 'Sosnovskaya'] },
        { m: ['스트렐초프', 'Streltsov'], f: ['스트렐초바', 'Streltsova'] }, { m: ['예르몰로프', 'Yermolov'], f: ['예르몰로바', 'Yermolova'] }, { m: ['아브데예프', 'Avdeev'], f: ['아브데예바', 'Avdeeva'] },
      ],
      given: {
        female: [
          ['아나스타샤', 'Anastasia'], ['나탈리야', 'Natalia'], ['소피야', 'Sofia'], ['베라', 'Vera'], ['알리사', 'Alisa'],
          ['옐레나', 'Elena'], ['다리야', 'Darya'], ['밀라나', 'Milana'], ['안나', 'Anna'], ['마리아', 'Maria'],
          ['예카테리나', 'Yekaterina'], ['타티아나', 'Tatiana'], ['올가', 'Olga'], ['스베틀라나', 'Svetlana'], ['빅토리아', 'Viktoria'],
          ['율리아', 'Yulia'], ['이리나', 'Irina'], ['폴리나', 'Polina'], ['크세니아', 'Ksenia'], ['마르가리타', 'Margarita'],
          ['마리나', 'Marina'], ['발레리아', 'Valeria'], ['갈리나', 'Galina'], ['나데즈다', 'Nadezhda'], ['류보프', 'Lyubov'],
          ['인나', 'Inna'], ['옥사나', 'Oksana'], ['야나', 'Yana'], ['니나', 'Nina'], ['알리나', 'Alina'],
          ['디아나', 'Diana'], ['예바', 'Eva'], ['안젤리나', 'Angelina'], ['바실리사', 'Vasilisa'], ['타이시야', 'Taisiya'],
          ['라리사', 'Larisa'], ['베로니카', 'Veronika'], ['안토니나', 'Antonina'], ['발렌티나', 'Valentina'], ['아리나', 'Arina'],
          ['일로나', 'Ilona'], ['조야', 'Zoya'], ['릴리야', 'Liliya'], ['마야', 'Maya'], ['타마라', 'Tamara'],
          ['클라라', 'Klara'], ['스네자나', 'Snezhana'], ['류드밀라', 'Lyudmila'], ['엘비라', 'Elvira'], ['이네사', 'Inessa'],
          ['카테리나', 'Katerina'], ['아젤라이다', 'Adelaida'], ['리자베타', 'Lizaveta'], ['예브게니야', 'Yevgeniya'], ['마르파', 'Marfa'],
          ['리디야', 'Lidiya'], ['알렉산드라', 'Alexandra'], ['울리야나', 'Ulyana'], ['예세니야', 'Yesenia'], ['미로슬라바', 'Miroslava'],
          ['블라다', 'Vlada'], ['레나타', 'Renata'], ['라다', 'Lada'], ['에벨리나', 'Evelina'], ['프라스코비야', 'Praskovya'],
          ['아브도티야', 'Avdotya'], ['스타니슬라바', 'Stanislava'],
        ],
        male: [
          ['알렉세이', 'Alexei'], ['드미트리', 'Dmitri'], ['이반', 'Ivan'], ['미하일', 'Mikhail'], ['니콜라이', 'Nikolai'],
          ['유리', 'Yuri'], ['레프', 'Lev'], ['세르게이', 'Sergei'], ['알렉산드르', 'Alexander'], ['안드레이', 'Andrei'],
          ['막심', 'Maxim'], ['블라디미르', 'Vladimir'], ['예브게니', 'Yevgeny'], ['데니스', 'Denis'], ['이고르', 'Igor'],
          ['올레그', 'Oleg'], ['안톤', 'Anton'], ['일리야', 'Ilya'], ['아르툠', 'Artyom'], ['빅토르', 'Viktor'],
          ['로만', 'Roman'], ['티무르', 'Timur'], ['파벨', 'Pavel'], ['보리스', 'Boris'], ['콘스탄틴', 'Konstantin'],
          ['루슬란', 'Ruslan'], ['레오니드', 'Leonid'], ['아나톨리', 'Anatoly'], ['뱌체슬라프', 'Vyacheslav'], ['바딤', 'Vadim'],
          ['마카르', 'Makar'], ['스테판', 'Stepan'], ['글렙', 'Gleb'], ['표트르', 'Pyotr'], ['이그나트', 'Ignat'],
          ['아르투르', 'Artur'], ['에두아르드', 'Eduard'], ['보그단', 'Bogdan'], ['야로슬라프', 'Yaroslav'], ['아르세니', 'Arseny'],
          ['티모페이', 'Timofei'], ['스타니슬라프', 'Stanislav'], ['발레리', 'Valery'], ['비탈리', 'Vitaly'], ['겐나디', 'Gennady'],
          ['루카', 'Luka'], ['마트베이', 'Matvei'], ['다닐', 'Danil'], ['알베르트', 'Albert'], ['펠릭스', 'Felix'],
          ['세바스티안', 'Sebastian'], ['마라트', 'Marat'], ['발렌틴', 'Valentin'], ['필립', 'Philipp'], ['키릴', 'Kirill'],
          ['게오르기', 'Georgy'], ['세묜', 'Semyon'], ['자하르', 'Zakhar'], ['다비드', 'David'], ['마르크', 'Mark'],
          ['로디온', 'Rodion'], ['아르카디', 'Arkady'], ['니키타', 'Nikita'], ['사벨리', 'Savely'], ['미론', 'Miron'],
          ['데미안', 'Demyan'], ['엘리세이', 'Yelisei'], ['로스티슬라프', 'Rostislav'], ['스뱌토슬라프', 'Svyatoslav'], ['야코프', 'Yakov'],
          ['바실리', 'Vasily'], ['표도르', 'Fyodor'], ['아파나시', 'Afanasy'], ['프로호르', 'Prokhor'], ['이노켄티', 'Innokenty'],
          ['예멜리안', 'Yemelyan'], ['니키포르', 'Nikifor'],
        ],
      },
    },
  },

  // 성별 기본 키 범위 [최소, 최대] cm (선택기에서 비워 두면 사용)
  heights: { female: [150, 178], male: [165, 192], nonbinary: [155, 185] },

  bodies: [
    { ko: '마른 체형', tag: 'slim' },
    { ko: '슬렌더', tag: 'slender' },
    { ko: '균형 잡힌 체형', tag: '' },
    { ko: '근육질', tag: 'muscular' },
    { ko: '탄탄한 체형', tag: 'toned' },
    { ko: '글래머러스', tag: 'curvy', g: ['female'] },
    { ko: '가녀린 체형', tag: 'petite', g: ['female', 'nonbinary'] },
    { ko: '어깨가 넓은 체형', tag: 'broad shoulders', g: ['male', 'nonbinary'] },
    { ko: '살집이 있는 체형', tag: 'plump' },
    { ko: '육감적인 체형', tag: 'curvy, thick thighs', g: ['female', 'nonbinary'] },
  ],

  jobs: [
    '대학원생', '바리스타', '강력계 형사', '외과의사', '일러스트레이터', '소설가', '바텐더', '변호사',
    '사진작가', '조향사', '피아니스트', '프로그래머', '헤드헌터', '꽃집 사장', '수의사', '호텔리어',
    '미술관 큐레이터', '고등학교 교사', '경호원', '번역가', '타투이스트', '셰프', '기자', '모델',
    '편의점 아르바이트생', '화이트 해커', '고서점 주인', '응급구조사', '웹툰 작가', '카페 사장',
    // 문화 · 방송 · 예술
    '건축가', '영화 감독', '유튜버', '인플루언서', '게임 스트리머', '연극 배우', '뮤지컬 배우', '인디 뮤지션',
    '특수분장사', '성우', 'PD', '아나운서', '기상캐스터', '음악 감독', '음향 감독', '영화 평론가', '디자이너',
    '메이크업 아티스트', '마술사', '동화 작가', '도예가', '현대 무용수', '게임 기획자', '프로게이머',
    // 클래식 음악
    '지휘자', '바이올리니스트', '첼리스트', '비올리스트', '더블베이시스트', '플루티스트', '오보이스트',
    '클라리네티스트', '클래식 작곡가', '피아노 조율사', '관악기 수리공', '악기점 사장',
    // 금융 · 법 · 공공
    '펀드매니저', '회계사', '국회의원 보좌관', '검사', '외교관', '국제회의 통역사', '경찰', '소방관',
    '특수 부대원', '사설탐정', '범죄 심리 프로파일러', '범죄자',
    // 의료 · 과학
    '흉부외과 의사', '정신과 의사', '심리상담사', '치위생사', '약사', '간호사', '법의학자',
    '천문학자', '해양 생물학자', '식물학자', '고고학자', '우주비행사',
    // 서비스 · 기타
    '항공기 조종사', '승무원', '스턴트맨', '타로술사', '장의사', '보석 감정사', '카지노 딜러', '특수청소부',
    '파티시에', '소믈리에', '웨딩 플래너', '유치원 교사', '도서관 사서', '여행 가이드', '피트니스 트레이너',
    '스포츠 에이전트', '스쿠버 다이버',
    // 운동선수 (올림픽 종목 위주)
    '카레이서', '종합격투기 선수', '피겨 스케이팅 선수', '승마 선수', '수영 선수', '양궁 선수', '펜싱 선수',
    '육상 선수', '체조 선수', '배구 선수', '농구 선수', '축구 선수', '테니스 선수', '유도 선수',
    '태권도 선수', '쇼트트랙 선수', '스노보드 선수', '클라이밍 선수',
  ],

  // hex: 기준 색상코드 (생성할 때마다 조금씩 변형), en: 프롬프트용 색 이름
  hairColors: [
    { ko: '흑발', en: 'black', hex: '#1C1C1E', natural: true },
    { ko: '짙은 갈색', en: 'dark brown', hex: '#3B2A22', natural: true },
    { ko: '밝은 갈색', en: 'light brown', hex: '#8A5F3F', natural: true },
    { ko: '금발', en: 'golden', hex: '#D9B061', natural: true },
    { ko: '백금발', en: 'platinum blonde', hex: '#E8DFC8', natural: true },
    { ko: '적갈색', en: 'auburn', hex: '#7A3A24', natural: true },
    { ko: '붉은 머리', en: 'red', hex: '#A8322A', natural: true },
    { ko: '애쉬 그레이', en: 'ash grey', hex: '#8E9194', natural: true },
    { ko: '은발', en: 'silver', hex: '#C4C8CE' },
    { ko: '백발', en: 'white', hex: '#EEEEEA' },
    { ko: '청발', en: 'blue', hex: '#3A62B0' },
    { ko: '남색', en: 'navy blue', hex: '#1F2B55' },
    { ko: '분홍색', en: 'pink', hex: '#E59AB5' },
    { ko: '보라색', en: 'purple', hex: '#6C4A9E' },
    { ko: '라벤더', en: 'lavender', hex: '#B7A3D8' },
    { ko: '민트색', en: 'mint', hex: '#8FD3C1' },
    { ko: '애쉬 그린', en: 'ash green', hex: '#7E9A8A' },
    { ko: '와인색', en: 'wine red', hex: '#6B1E33' },
    { ko: '주황색', en: 'orange', hex: '#E0782F' },
  ],

  // 첫 항목(없음)이 뽑힐 확률은 app.js에서 조정. {c} = 두 번째 색 이름
  hairExtras: [
    { ko: '', tag: '' },
    { ko: '이너컬러', tag: 'colored inner hair, {c} inner hair' },
    { ko: '브릿지', tag: 'streaked hair, {c} streaks' },
    { ko: '그라데이션', tag: 'gradient hair, {c} hair tips' },
    { ko: '투톤', tag: 'two-tone hair, {c} hair' },
  ],

  // tag에 NovelAI 가중치 문법(0.7::tag::)을 그대로 쓸 수 있음
  bangs: [
    { ko: '일자 앞머리', tag: 'blunt bangs' },
    { ko: '시스루 앞머리', tag: 'wispy bangs' },
    { ko: '옆으로 넘긴 앞머리', tag: 'swept bangs' },
    { ko: '가르마 앞머리', tag: 'parted bangs' },
    { ko: '눈 사이로 흘러내린 앞머리', tag: 'hair between eyes, 1.5::hair strands::' },
    { ko: '한쪽 눈을 가리는 앞머리', tag: 'hair over one eye' },
    { ko: '눈을 덮는 긴 앞머리', tag: '0.8::hair over eyes::' },
    { ko: '이마를 드러낸 올백', tag: '0.7::hair slicked back::, 2::hair strands::, forehead' },
  ],

  // lv: 길이 단계 (스타일 선택 시 사용), len: 색 앞에 붙는 길이 단어, cut: 추가 태그
  hairLengths: [
    { ko: '숏컷', len: 'short', cut: '', lv: 0 },
    { ko: '픽시컷', len: 'short', cut: 'pixie cut', lv: 0 },
    { ko: '단발', len: 'short', cut: 'bob cut', lv: 1 },
    { ko: '중단발', len: 'medium', cut: '', lv: 2 },
    { ko: '장발', len: 'long', cut: '', lv: 3 },
    { ko: '허리까지 오는 장발', len: 'very long', cut: '', lv: 4 },
  ],

  // minLv: 이 길이 이상일 때만 선택
  hairStyles: [
    { ko: '생머리', tag: 'straight hair' },
    { ko: '자연스러운 웨이브', tag: 'wavy hair' },
    { ko: '곱슬머리', tag: 'curly hair' },
    { ko: '부스스한 머리', tag: 'messy hair' },
    { ko: '울프컷', tag: 'wolf cut', minLv: 1 },
    { ko: '하나로 묶은 포니테일', tag: 'ponytail', minLv: 2 },
    { ko: '낮게 묶은 머리', tag: 'low ponytail', minLv: 2 },
    { ko: '반묶음', tag: 'half updo', minLv: 2 },
    { ko: '올림머리', tag: 'hair bun', minLv: 2 },
    { ko: '땋은 머리', tag: 'braid', minLv: 3 },
    { ko: '트윈테일', tag: 'twintails', minLv: 3 },
  ],

  // odd: 오드아이 (다른 색 두 개를 뽑음)
  eyeColors: [
    { ko: '흑색', en: 'black', hex: '#1E1B1A', natural: true },
    { ko: '갈색', en: 'brown', hex: '#5A3B26', natural: true },
    { ko: '호박색', en: 'amber', hex: '#C7862E', natural: true },
    { ko: '회색', en: 'grey', hex: '#7D8388', natural: true },
    { ko: '푸른색', en: 'blue', hex: '#3E6FB8', natural: true },
    { ko: '하늘색', en: 'light blue', hex: '#8DBBE0', natural: true },
    { ko: '녹색', en: 'green', hex: '#4E8A4A', natural: true },
    { ko: '애쉬 그린', en: 'ash green', hex: '#7C9A88', natural: true },
    { ko: '청록색', en: 'aqua', hex: '#3FA7A6' },
    { ko: '금색', en: 'golden', hex: '#D9A92E' },
    { ko: '붉은색', en: 'red', hex: '#B3262E' },
    { ko: '보라색', en: 'purple', hex: '#7A4FB0' },
    { ko: '분홍색', en: 'pink', hex: '#DC7FA3' },
    { ko: '오드아이', odd: true },
  ],

  eyeShapes: [
    { ko: '올라간 눈매', tag: '0.8::tsurime::' },
    { ko: '처진 눈매', tag: '0.8::tareme::' },
    { ko: '날카로운 눈매', tag: 'sharp eyes' },
    { ko: '동그란 눈', tag: 'round eyes' },
    { ko: '나른한 눈매', tag: '0.6::half-closed eyes::' },
    { ko: '게슴츠레한 눈', tag: '0.5::jitome::' },
    { ko: '가늘게 뜬 눈', tag: 'narrowed eyes' },
    { ko: '삼백안', tag: 'sanpaku' },
  ],

  // mature: true 인상이면 나이와 상관없이 mature female/male 태그를 붙임
  impressions: [
    { ko: '차갑고 도도한' }, { ko: '온화하고 부드러운' }, { ko: '무심한' }, { ko: '날카로운' },
    { ko: '나른한' }, { ko: '장난기 어린' }, { ko: '순해 보이는' }, { ko: '늘 피곤해 보이는' },
    { ko: '화려한' }, { ko: '단정한' }, { ko: '어딘가 쓸쓸한' },
    { ko: '위압감 있는', mature: true }, { ko: '성숙하고 차분한', mature: true }, { ko: '노련해 보이는', mature: true },
    { ko: '청초한' }, { ko: '천진난만한' }, { ko: '매혹적인' }, { ko: '관능적인' }, { ko: '맹한' },
    { ko: '허술해 보이는' }, { ko: '금욕적인' }, { ko: '공허한' }, { ko: '이지적인' },
  ],

  skins: [
    { ko: '창백한 피부', tag: 'pale skin' },
    { ko: '하얀 피부', tag: 'fair skin' },
    { ko: '건강한 피부톤', tag: '' },
    { ko: '구릿빛 피부', tag: 'tan' },
    { ko: '어두운 피부', tag: 'dark skin' },
  ],

  marks: [
    { ko: '눈 밑 점', tag: 'mole under eye' },
    { ko: '입가 점', tag: 'mole under mouth' },
    { ko: '목덜미 점', tag: 'mole on neck' },
    { ko: '안경', tag: 'glasses' },
    { ko: '귀 피어싱', tag: 'ear piercing' },
    { ko: '얼굴의 옅은 흉터', tag: 'scar on face' },
    { ko: '주근깨', tag: 'freckles' },
    { ko: '뾰족한 송곳니', tag: 'fang' },
    { ko: '긴 속눈썹', tag: 'long eyelashes' },
    { ko: '팔의 문신', tag: 'arm tattoo' },
    { ko: '짙은 다크서클', tag: 'eyebags' },
    { ko: '볼의 반창고', tag: 'bandaid on face' },
    { ko: '혀 피어싱', tag: 'tongue piercing' },
    { ko: '목의 문신', tag: 'neck tattoo' },
    { ko: '등의 문신', tag: 'back tattoo' },
    { ko: '배의 문신', tag: 'stomach tattoo' },
    { ko: '허벅지 문신', tag: 'thigh tattoo' },
    { ko: '손목 문신', tag: 'wrist tattoo' },
    { ko: '어깨 문신', tag: 'shoulder tattoo' },
    { ko: '손등 문신', tag: 'hand tattoo' },
    { ko: '가슴팍 문신', tag: 'chest tattoo' },
    { ko: '수술 자국', tag: 'scar' },
    { ko: '백반증', tag: 'vitiligo' },
    { ko: '작은 입', tag: 'small mouth', grp: 'mouth' },
    { ko: '큰 입', tag: 'wide mouth', grp: 'mouth' },
  ],

  // {c} = 옷 색 (clothColors에서 랜덤, 한 벌 안에서는 같은 색)
  fashions: [
    { ko: '캐주얼', tag: '{c} hoodie, blue jeans' },
    { ko: '정장', tag: '{c} suit, white collared shirt, necktie' },
    { ko: '스트릿', tag: '{c} oversized jacket, cargo pants, sneakers' },
    { ko: '댄디', tag: 'white collared shirt, {c} cardigan, slacks' },
    { ko: '고딕', tag: 'gothic, black clothes, choker' },
    { ko: '미니멀', tag: '{c} shirt, black pants' },
    { ko: '스포티', tag: '{c} track jacket, {c} track pants' },
    { ko: '클래식', tag: '{c} turtleneck, long coat' },
    { ko: '빈티지', tag: '{c} knit sweater, corduroy pants' },
    { ko: '페미닌', tag: '{c} blouse, long skirt', g: ['female', 'nonbinary'] },
    { ko: '오피스룩', tag: 'white blouse, {c} pencil skirt, office lady', g: ['female'] },
    { ko: '워크웨어', tag: '{c} work jacket, cargo pants, boots', g: ['male', 'nonbinary'] },
    { ko: '히피', tag: 'hippie, headband, {c} flared pants' },
    { ko: '컨트리', tag: '{c} plaid shirt, overalls, straw hat' },
    { ko: '레트로', tag: '{c} windbreaker, high-waist pants' },
    { ko: '바이커룩', tag: 'biker clothes, black leather jacket, {c} jeans, boots' },
    { ko: '메탈룩', tag: 'black band shirt, studded belt, spiked bracelet, black leather pants' },
    { ko: '블록코어', tag: '{c} soccer uniform, track pants, sneakers' },
    { ko: '수도복', tag: 'nun, habit', g: ['female', 'nonbinary'] },
    { ko: '수도복', tag: 'cassock, priest', g: ['male', 'nonbinary'] },
    { ko: '웨스턴', tag: 'cowboy western, cowboy hat, {c} vest, cowboy boots' },
    { ko: '하라주쿠', tag: 'harajuku fashion, colorful clothes, layered clothes, hair ornament' },
    { ko: 'EMO 패션', tag: 'emo fashion, black hoodie, striped arm warmers, wristband' },
    { ko: '젠더리스', tag: 'oversized {c} shirt, wide-leg pants' },
    { ko: '보헤미안', tag: 'bohemian, fringe, {c} layered clothes' },
    { ko: 'Y2K', tag: '{c} crop top, low-rise jeans, platform shoes' },
    { ko: '에스닉', tag: 'ethnic clothes, embroidered {c} tunic' },
    { ko: '마린룩', tag: 'striped shirt, white pants, sailor hat' },
    { ko: '하이패션', tag: 'high fashion, {c} designer coat' },
    { ko: '밀리터리', tag: 'military jacket, {c} cargo pants, combat boots' },
    { ko: '테크웨어', tag: 'techwear, black windbreaker, straps, cargo pants' },
    { ko: '고스', tag: 'goth fashion, black lipstick, fishnets, platform boots' },
    { ko: '로리타', tag: 'lolita fashion, {c} frilled dress, bonnet', g: ['female', 'nonbinary'] },
  ],
  clothColors: ['black', 'white', 'grey', 'navy', 'beige', 'brown', 'dark green', 'burgundy', 'cream'],

  voices: [
    '낮고 허스키한 목소리', '맑고 높은 목소리', '나긋나긋한 목소리', '건조하고 무뚝뚝한 목소리',
    '부드러운 중저음', '발랄하고 톤이 높은 목소리', '느릿하고 나른한 목소리', '또렷하고 단호한 목소리',
    '카랑카랑한 목소리', '중성적인 목소리', '금속성 음색',
  ],

  traits: [
    '츤데레', '다정함', '냉소적', '능글맞음', '무뚝뚝함', '완벽주의', '소심함', '자존심이 셈',
    '호기심이 많음', '집착이 강함', '낙천적', '계산적', '충동적', '느긋함', '책임감이 강함',
    '눈치가 빠름', '허당', '독설가', '헌신적', '질투가 많음', '겁이 많음', '대담함', '예의 바름',
    '제멋대로', '외로움을 잘 탐', '감정 표현이 서툶', '장난기가 많음', '이성적', '감성적', '고집이 셈',
    '정이 많음', '탐미주의', '감정을 숨김', '회복탄력성이 높음',
    '권태로움', '수줍음', '소유욕이 강함', '덜렁댐', '어수룩함', '순진함',
    '염세적', '독립적', '자기희생적', '자기중심적', '우유부단함', '승부욕이 강함',
    '예민함', '눈치 없음', '솔직함', '짓궂음', '고지식함', '건방짐',
    '거만함', '게으름', '부지런함', '능청스러움', '뻔뻔함', '무던함',
  ],

  // 내면: 겉으로 잘 드러나지 않는 핵심 욕구 · 두려움 · 방어기제
  inners: [
    '통제 욕구', '통제 상실 공포', '방어적 공격성', '친절 강박', '소속 욕구', '자기 검열',
    '인정 욕구', '유기 불안', '과잉 책임감', '회피 성향', '자기 파괴 충동', '완벽주의적 강박',
    '보호 욕구', '의존적', '자극 추구', '위험 추구', '죄책감', '피해의식',
    '무기력', '감정 억제', '깊은 관계 회피', '열등감', '이상주의', '허무주의',
    '인간 불신', '구원 욕구', '위선자', '반골',
  ],

  gaps: [
    '겉으론 차갑지만 속은 여림', '늘 웃지만 속을 알 수 없음', '무심한 척하지만 전부 기억함',
    '허술해 보이지만 치밀함', '어른스러워 보이지만 어리광이 많음', '강해 보이지만 혼자 있는 걸 무서워함',
    '예의 바르지만 선을 긋는 데 능함', '가벼워 보이지만 한 사람만 봄', '순해 보이지만 화나면 제일 무서움',
  ],

  values: [
    '약속은 반드시 지킨다', '결과가 과정을 증명한다', '내 사람은 끝까지 지킨다', '자유가 무엇보다 중요하다',
    '돈은 배신하지 않는다', '진실은 언젠가 드러난다', '오늘을 즐기는 것이 최선이다', '감정보다 이성이 우선이다',
    '받은 만큼 돌려준다', '누구에게도 빚지지 않는다', '사랑은 증명하는 것이다', '할 수 있을 때 최선을 다한다',
  ],

  speeches: [
    '누구에게나 존댓말', '반말과 존댓말을 섞어 씀', '짧고 단답형', '느릿하게 늘어지는 말투',
    '사투리가 섞인 말투', '비꼬는 말투', '말끝을 흐림', '다정한 반말', '장난스러운 말투',
    '격식 있는 문어체', '말수가 적고 핵심만 말함', '혼잣말이 많음',
    '살가운 말투', '과장된 말투', '새침한 말투', '장황하고 비유가 많음', '냉소적인 말투',
  ],

  likes: [
    '비 오는 날', '블랙커피', '단 음식', '고양이', '오래된 영화', '새벽 산책', '향초', '따뜻한 차',
    '칭찬받는 것', '조용한 서점', '바다', '위스키', '손편지', '빈티지 소품', '매운 음식', '별 보기',
    '강아지', '늦잠', '재즈', '겨울',
    '민트초코', '드라이브', '식물 가꾸기', '정리정돈', '필기구 수집', '사진 찍기',
    '혼자 있는 시간', '새 책 냄새', 'LP판', '요리하는 것', '비행기 창가 자리', '낮잠',
    '푹신한 이불', '샤워 후 마시는 맥주', '새로운 도전', '햇볕 쬐기', 'ASMR', '추리소설',
    '보드게임', '즉흥적인 여행', '비 오는 날 흙냄새', '스킨십', '눈 오는 날', '전시회 관람',
    '심야 라디오', '가죽 냄새', '가벼운 장난', '드립 커피', '오래된 물건',
  ],

  dislikes: [
    '시끄러운 곳', '거짓말', '오이', '기다리는 것', '벌레', '무례한 사람', '동정받는 것',
    '계획이 틀어지는 것', '뜨거운 음식', '병원', '천둥', '아침', '사람 많은 곳', '단 음식',
    '여름', '매운 음식', '빚지는 것', '고양이',
    '파인애플 피자', '민트초코', '고수', '담배 냄새', '습하고 끈적이는 날씨', '스킨십',
    '잔소리', '갑자기 걸려오는 전화', '지나친 관심', '뒷담화', '땀 흘리는 것', '맛없는 음식으로 배 채우는 것',
    '흐지부지 끝나는 것', '규칙에 얽매이는 것', '반복되는 일상', '당일 약속 취소', '눈을 똑바로 쳐다보는 것', '너무 밝은 형광등 불빛',
    '쓴 약', '선을 넘는 장난', '어색한 침묵', '훈수 두는 사람', '답장 늦는 것', '복잡한 설명',
    '밀가루 음식', '더러운 책상',
  ],

  hobbies: [
    '독서', '요리', '러닝', '사진 촬영', '보드게임', '영화 감상', '식물 키우기', '뜨개질', '복싱',
    '드라이브', '게임', '그림 그리기', '레코드 수집', '베이킹', '수영', '퍼즐', '칵테일 만들기',
    '캠핑', '피아노 연주', '서예',
    '등산', '클라이밍', '자전거 타기', '서핑', '스쿠버다이빙', '낚시',
    '스케이트보드', '요가', '필라테스', '도자기 공예', '목공', '가죽 공예',
    '향수 만들기', '미니어처 조립', '프라모델 조립', '다이어리 꾸미기', '체스', '타로카드 점보기',
    '외국어 공부', '맛집 탐방', '카페 투어', '전시회 관람', '피규어 수집', '빈티지 옷 쇼핑',
    '블로그 운영', '브이로그 촬영', '웹소설 읽기', '만화책 수집', '십자수', '일기 쓰기',
    '테니스', '골프', '볼링', '방탈출 카페 가기', '천체 관측', '꽃꽂이',
    '풍경 스케치', '와인 시음', '스도쿠', '스쿠터 타기', 'LP 청음', '야구 관람',
    '스트릿 댄스', '캘리그라피', '인테리어 소품 수집', '폴라로이드 사진 찍기', '시 쓰기', '지도 그리기',
    '노래 부르기', '화폐 · 동전 수집', '수수께끼 풀기', '낮잠', '불멍', '자수 놓기',
    '유적 · 폐허 탐험',
  ],

  habits: [
    '생각할 때 입술을 깨문다', '거짓말할 때 눈을 피한다', '긴장하면 머리카락을 만지작거린다',
    '무의식적으로 펜을 돌린다', '잠들기 전 일기를 쓴다', '초조하면 손톱을 뜯는다',
    '기분 좋으면 콧노래를 부른다', '상대의 말을 곱씹듯 따라 한다', '불안하면 손가락으로 톡톡 두드린다',
    '커피를 하루 네 잔 이상 마신다', '물건을 정해진 자리에만 둔다', '한숨을 자주 쉰다',
    '습관적으로 팔짱을 낀다', '대화할 때 시선을 피한다',
  ],

  // 체향: 탑 노트(top) 1개 + 베이스 노트(base) 1개
  // top / base: 그 계열의 향료가 탑 노트 / 베이스 노트로 나올 수 있는지
  scentFamilies: [
    {
      ko: '시트러스 & 그린', en: 'Citrus & Green', top: true,
      notes: ['베르가못', '비터 오렌지', '자몽', '갈바눔', '페퍼민트', '레몬', '유자', '라임', '네롤리', '바질', '로즈마리', '그린 티', '무화과 잎'],
    },
    {
      ko: '플로럴 & 프루티', en: 'Floral & Fruity', top: true, base: true,
      notes: ['튜베로즈', '은방울꽃', '아이리스', '무화과', '블랙베리', '장미', '자스민', '작약', '프리지아', '금목서', '라일락', '라벤더', '복숭아', '서양배', '블랙커런트'],
    },
    {
      ko: '우디 & 스파이시', en: 'Woody & Spicy', base: true,
      notes: ['샌달우드', '시더우드', '패출리', '핑크 페퍼', '베티버', '오드(침향)', '카다멈', '시나몬', '사이프러스', '과이악우드', '사프란'],
    },
    {
      ko: '머스크 & 발사믹', en: 'Musk & Balsamic', base: true,
      notes: ['화이트 머스크', '애니멀릭 머스크', '앰버그리스', '바닐라', '통카빈', '벤조인', '라브다넘', '스웨이드', '파우더리 머스크', '꿀', '비누 향', '섬유유연제', '베이비 파우더'],
    },
    {
      ko: '특수 / 이색', en: 'Special & Ozonic', top: true, base: true,
      notes: ['오조닉', '타바코', '코냑', '인센스', '페트리코', '씨솔트', '미네랄', '메탈릭', '오래된 종이', '럼', '에스프레소', '눈 내린 공기'],
    },
  ],

  weaknesses: [
    '술에 약함', '칭찬에 약함', '동물 앞에서 무장해제', '거절을 못 함', '길치', '기계치',
    '추위를 많이 탐', '눈물에 약함', '간지럼을 많이 탐', '고소공포증',
    '더위를 많이 탐', '수영을 전혀 못 함', '거짓말하면 얼굴에 다 티가 남', '귀가 얇음', '피를 보면 기절함', '어둠을 무서워함',
    '아이들을 대하기 어려워함', '매운 것을 전혀 못 먹음', '끔찍한 요리 실력', '심한 악필', '사람 이름과 얼굴을 잘 못 외움', '스킨십을 받으면 고장 남',
    '미인 · 미남에게 한없이 약함', '물건을 자주 잃어버림', '아침에 쉽게 못 일어남', '경제 관념이 없음', '벌레만 보면 굳어버림', '폐소공포증',
    '멀티태스킹 불가', '눈치가 심하게 없음', '집중하면 주변 소리를 못 들음', '선단공포증 (뾰족한 것을 무서워함)', '무서운 이야기나 영화에 기겁함', '단순한 도발에 쉽게 넘어감',
    '끔찍한 패션 감각', '불면증', '심해공포증 (깊은 물을 무서워함)', '체력이 몹시 약함', '부탁하는 걸 죽기보다 싫어함', '정리에 소질이 없음',
    '타인의 시선을 과하게 의식함', '알약을 잘 못 삼킴',
    '몽유병', '기가 약함', '동물들에게 인기 없음', '마취가 잘 듣지 않음', '약물 내성', '잠버릇이 심함',
    '색약', '건망증', '잔병치레가 많음', '알레르기', '카페인에 예민함',
  ],

  families: [
    '외동', '화목한 집안의 첫째', '형제 많은 집안의 막내', '쌍둥이 동생이 있음', '편부 가정',
    '편모 가정', '조부모 손에 자람', '연락을 끊은 가족', '재벌가의 막내', '입양됨',
    '이복형제가 있음', '가족을 모두 잃음',
    '재혼 가정', '위탁 가정',
  ],

  traumas: [
    '어린 시절 방치됨', '가까운 사람의 배신', '화재 사고 생존자', '소중한 사람을 눈앞에서 잃음',
    '오랫동안 괴롭힘을 당함', '물에 빠진 경험 (물 공포)', '부모의 과도한 기대', '연인의 잠적',
    '납치당한 경험', '좁은 곳에 갇힌 기억 (폐소공포)', '큰 실패로 모든 것을 잃음', '없음 (본인은 그렇게 믿음)',
  ],

  secrets: [
    '몰래 팬픽을 씀', '사실 겁이 아주 많음', '갚지 못한 빚이 있음', '과거에 다른 이름으로 살았음',
    '누군가를 오래 짝사랑 중', '인형 없이는 잠들지 못함', '숨기고 싶은 전과가 있음',
    '가족에게 숨긴 직업이 있음', '사실 요리를 전혀 못 함', '남에게 말 못 한 지병이 있음',
    '익명으로 꾸준히 기부 중', '유명 인플루언서의 부계정 주인',
    '실패에 대한 공포', '사생아', '서자',
  ],

  loves: [
    '연애는 사치라고 생각함', '한번 빠지면 전부를 거는 타입', '천천히 스며드는 타입',
    '먼저 다가가지 못하는 타입', '표현은 서툴지만 행동으로 보여줌', '밀당을 즐김',
    '질투를 숨기지 못함', '첫사랑을 잊지 못함', '결혼을 전제로만 만남', '상대에게 맞춰주는 타입',
  ],

  attachments: [
    '안정형 (Secure)',
    '불안형 (Anxious)',
    '회피형 (Avoidant)',
    '혼란형 (Fearful-Avoidant)',
  ],

  // ---------- NSFW (BDSM 성향 테스트 결과 항목 참고) ----------
  // side: dom / sub / any(어느 쪽이든 가능)
  bdsmPositions: [
    { ko: '돔 (Dominant)', side: 'dom' },
    { ko: '섭 (Submissive)', side: 'sub' },
    { ko: '스위치 (Switch)', side: 'switch' },
  ],
  bdsmRoles: [
    { ko: '도미넌트', side: 'dom' },
    { ko: '사디스트', side: 'dom' },
    { ko: '브랫 테이머', side: 'dom' },
    { ko: '마스터/미스트리스', side: 'dom' },
    { ko: '오너', side: 'dom' },
    { ko: '리거', side: 'dom', rope: true },
    { ko: '헌터 (Primal)', side: 'dom' },
    { ko: '디그레이더', side: 'dom' },
    { ko: '서브미시브', side: 'sub' },
    { ko: '마조히스트', side: 'sub' },
    { ko: '브랫', side: 'sub' },
    { ko: '슬레이브', side: 'sub' },
    { ko: '펫', side: 'sub' },
    { ko: '로프 버니', side: 'sub', rope: true },
    { ko: '프레이 (Primal)', side: 'sub' },
    { ko: '디그레이디', side: 'sub' },
    { ko: '익스페리멘탈리스트', side: 'any' },
    { ko: '관음증', side: 'any' },
    { ko: '노출증', side: 'any' },
    { ko: '논모노가미스트', side: 'any' },
    { ko: '바닐라', side: 'any' },
    { ko: '대디/마미', side: 'dom' },
    { ko: '케어기버', side: 'dom' },
  ],
  nsfwStyles: [
    '다정하고 배려 깊음', '집요함', '장난스러움', '말로 몰아붙이는 타입', '조용하지만 격렬함',
    '수줍어하지만 적극적', '느긋하게 애태움', '규칙과 의식을 중시함', '평소와 정반대',
    '이성을 잃고 집착함', '서투름', '시각적인 자극(거울, 지켜보기 등)에 약함',
    '상대의 페이스에 쉽게 말려들어감', '상대방이 무너지는 반응을 즐김', '철저하게 통제하고 지배함',
  ],
  // tag: 한계선과 겹치는지 확인할 때 쓰는 분류
  nsfwPlays: [
    { ko: '본디지 (결박)', tag: 'rope' },
    { ko: '스팽킹', tag: 'pain' },
    { ko: '칭찬 (Praise)' },
    { ko: '초커 · 목줄' },
    { ko: '명령과 복종' },
    { ko: '눈가리개' },
    { ko: '애태우기 (Teasing)' },
    { ko: '흔적 남기기', tag: 'mark' },
    { ko: '역할극' },
    { ko: '감각 차단' },
    { ko: '말로 몰아붙이기', tag: 'verbal' },
    { ko: '긴 애프터케어' },
    { ko: '오르가즘 컨트롤 · 방치' },
    { ko: '소리 참게 하기' },
    { ko: '깨물기', tag: 'mark' },
    { ko: '거울 플레이' },
    { ko: '워터 플레이' },
    { ko: '브레스 컨트롤', tag: 'breath' },
    { ko: '코스튬 플레이' },
    { ko: '기구 사용' },
    { ko: '공개된 장소', tag: 'public' },
    { ko: '언어적 모욕', tag: 'verbal' },
  ],
  nsfwLimits: [
    { ko: '흔적이 남는 행위', tag: 'mark' },
    { ko: '강한 고통', tag: 'pain' },
    { ko: '언어적 모욕', tag: 'verbal' },
    { ko: '결박', tag: 'rope' },
    { ko: '공개된 장소', tag: 'public' },
    { ko: '사진 · 영상 촬영' },
    { ko: '제3자 개입' },
    { ko: '없음 (대화로 조율)' },
    { ko: '브레스 컨트롤', tag: 'breath' },
    { ko: '나이프 플레이', tag: 'knife' },
  ],
  nsfwSpots: [
    '귀', '목덜미', '허리', '쇄골', '손목', '등', '허벅지 안쪽', '아랫배', '무릎 뒤쪽', '날개뼈', '발목', '귓바퀴',
    '유두', '옆구리', '배꼽 주변', '손가락 사이', '겨드랑이', '팔꿈치 안쪽', '입천장',
  ],
  // 신체 특이사항: anat(f/m)가 있으면 그 신체에만, grp가 같으면 한 번에 하나만
  nsfwBodies: [
    { ko: '함몰유두' }, { ko: '배꼽 피어싱' }, { ko: '유두 피어싱' },
    { ko: '흔적이 잘 남는 피부' }, { ko: '쉽게 붉어지는 피부' },
    { ko: '무모증', grp: 'pubic' }, { ko: '브라질리언 왁싱', grp: 'pubic' }, { ko: '음모가 짙고 숱이 많음', grp: 'pubic' },
    { ko: '쉽게 젖음', anat: 'f', grp: 'wet' }, { ko: '건조한 편 (윤활제 필요)', anat: 'f', grp: 'wet' },
    { ko: '명기', anat: 'f' }, { ko: '안쪽이 유난히 좁음', anat: 'f' },
    { ko: '거근', anat: 'm' }, { ko: '포경 수술 완료', anat: 'm', grp: 'foreskin' },
    { ko: '자연 포경 · 노포경', anat: 'm', grp: 'foreskin' }, { ko: '사정량이 많음', anat: 'm' },
  ],

  // 이미지 프롬프트 표정 (표정 재생성 버튼으로 바뀌는 부분)
  // 기본 표정 1개 + 50% 확률로 보조 표정 1개
  expressions: [
    'expressionless', 'light smile', 'smile', 'gentle smile', 'smirk', 'smug', 'pout',
    'serious', 'annoyed', 'bored', 'surprised', 'frown', 'closed mouth', 'parted lips',
  ],
  expressionMods: ['shy', 'blush', 'embarrassed', 'sleepy', 'nervous', 'light blush'],
};
